### ISSUE TITLE
Direct Messaging

### ISSUE THREAD

**Issue by vhpoet** [terkelg/ramme#1]
Thanks for this awesomeness, the app looks and behaves great. 

Couldn't miss the opportunity to open the first issue / feature request. It would be really great to be able to send and receive direct messages. A lot of Instagrammers/photographers use direct messages quite a lot.

Cheers from http://instagram.com/vhpoet

**Comment by terkelg** [comment]
Thanks for the kind words.

I'll love to add features such as photo upload, stories and direct messaging.
However, I'm not sure Instagram allows that at the moment, since I have to reverse engineer the API. 

I'm looking for a solution

**Comment by vhpoet** [comment]
@terkelg yea I think the only way would be to use their private API.

**Comment by hrbrt** [comment]
Don't forget: Instagram Kills Off Feed Reading Apps https://techcrunch.com/2015/11/17/just-instagram/

**Comment by terkelg** [comment]
This won't effect Ramme, since I use their own website
