### ISSUE TITLE
Tray icon invisible on Linux

### ISSUE THREAD

**Issue by theel0ja** [terkelg/ramme#100]
Ramme's tray icon is invisible.

![image](https://cloud.githubusercontent.com/assets/5832930/23830059/d8124a72-0709-11e7-910d-ce031f3b18aa.png)

OS: Linux Mint 18.1 Cinnamon Edition
Theme: Adapta-Nokto
Icons: Numix-Circle

**Comment by Fincer** [comment]
Happens on Arch Linux, too. (KDE5 Plasma desktop)

**Comment by terkelg** [comment]
@Fincer can you maybe take a look at this? I don't have a linux desktop

**Comment by Fincer** [comment]
I could but do you have any instructions how to debug the program? I'm currently using AUR version of the program which is based on the Ramme .deb installation package. 

I don't have any terminal output for ramme executable and when I try gdb tool (GNU Debugger) it complains that the executable is not compiled with debug symbols.

You may consider setting up a virtual linux desktop environment (VirtualBox + Lubuntu) for quick testing purposes if you care.

One thing that came to mind: 

there have been issues like [this one (electron)](https://github.com/electron/electron/issues/5050) so this *may* relate to electron after all. Hard to say right now.

**Comment by bil-elmoussaoui** [comment]
It's seems that electron's nativeImage returns an empty object when we use nativeImage.createFromPath. There's an open issue about that.
Also, the tray icons are not perfect for now (the icon sizes shouldn't be 18x18)
I will see how i can workaround this

**Comment by bil-elmoussaoui** [comment]
Fixed that on master!

**Comment by bil-elmoussaoui** [comment]
Can you reproduce this issue with the latest version?

**Comment by truckerboy** [comment]
I can confirm this issue appears fixed in version 3.2.1 on Ubuntu 16.10 64 bit. Thanks!

**Comment by theel0ja** [comment]
![image](https://cloud.githubusercontent.com/assets/5832930/26523331/1e6358ae-431e-11e7-9d90-de1ad46f99b2.png)

It's visible :)

**Comment by bil-elmoussaoui** [comment]
Perfect! We will try to make it look better on the next versions :)
