### ISSUE TITLE
No tray/panel icon No way to quit

### ISSUE THREAD

**Issue by Caver1** [terkelg/ramme#101]
Using Ramme 3.0.3 with Ubuntu 16.04. I get no tray/panel icon when Ramme is open and get no way to quit Ramme. Can only close window.
I have to kill the Ramme process to quit.

**Comment by bil-elmoussaoui** [comment]
Do you mean that the try icon is not shown at all or it's just invisible?

**Comment by Caver1** [comment]
There is no tray icon.

**Comment by bil-elmoussaoui** [comment]
Do you have libappindicator installed on your system?

**Comment by Caver1** [comment]
Yes libappindicator1 and libappindicator3-1

**Comment by bil-elmoussaoui** [comment]
what if you run the application from terminal using `env XDG_CURRENT_DESKTOP=Unity ramme`?

**Comment by Caver1** [comment]
I ran  env XDG_CURRENT_DESKTOP=Unity ramme. Ramme opens still no tray icon.

**Comment by bil-elmoussaoui** [comment]
Do you use any Electron apps with tray icons working correctly ? if so can you tell me which ones ? 
As we do follow the documentation of how to create a tray icon, but i doesn't work on all Linux distro

**Comment by alpvonkri** [comment]
I reported the same thing since Issue #82 
The issue was closed, but still not solved, no tray icon at all.

**Comment by bil-elmoussaoui** [comment]
@alpvonkri it's not the same issue. Your issue has been fixed, if there's something else please open a new issue. The tray icon should work now on Linux if not, it's electron's issue...

**Comment by alpvonkri** [comment]
@bil-elmoussaoui It is the same issue started in #82  with the app being unable to run because an error with the tray icon, and when they fixed the unability to run, it never showed the tray icon (still present in 3.2.0), but whatever, I do not plan to argue about it, and if it's an electron issue, it's weird that version 2.3.0 does show the tray icon (I've been stuck in that version since then)

**Comment by bil-elmoussaoui** [comment]
Well, the 2.3.0 doesn't use the same electron versions as 3.2.0. We use the latest version. But for some reasons whenever we create an image it's return an empty object on Linux. But don't worry about it, i will do my best to fix it

**Comment by alpvonkri** [comment]
@bil-elmoussaoui We do REALLY appreciate your and everyone's work, keep it up.

**Comment by bil-elmoussaoui** [comment]
Can you reproduce this issue with the new version?

**Comment by Caver1** [comment]
Just realized that there was a new version, thanks.
Will try it and let you know.

**Comment by Caver1** [comment]
Yes. With 3.2.1 I now have a tray icon.
Thanks

**Comment by bil-elmoussaoui** [comment]
Perfect :+1: Please report any other issues that you might have
thanks for testing
