### ISSUE TITLE
Unreadable text on dark mode

### ISSUE THREAD

**Issue by Nhanderu** [terkelg/ramme#102]
This is just a small detail, but it is always worth pointing it out. 😉 

My profile page:
![normal-mode](https://cloud.githubusercontent.com/assets/7098211/23976065/d9a95b52-09c3-11e7-959d-9c72f28ebca8.png)

My profile page on dark mode:
![dark-mode](https://cloud.githubusercontent.com/assets/7098211/23976066/d9ae3e88-09c3-11e7-844b-8272c62fbbb1.png)

The texts on the "Edit Profile" button and the links below the username are unreadable.

I do not know if it is relevant, but I am using the 3.0.3 version of Ramme on my Antergos Gnome.

**Comment by terkelg** [comment]
Thanks, I'm going to take a look at this.

**Comment by bil-elmoussaoui** [comment]
This fix changed the color of the normal theme too :/

**Comment by bil-elmoussaoui** [comment]
Already fixed on master
