### ISSUE TITLE
Can't go to upload page

### ISSUE THREAD

**Issue by rohmanhm** [terkelg/ramme#103]
When I click Photo icon, it's not going to upload or create page (stuck in current page).
Just the photo icon be darken

![image](https://cloud.githubusercontent.com/assets/7524911/24071286/1d42a640-0c01-11e7-92ab-5395a69e5958.png)

**Comment by anatolinicolae** [comment]
Strange thing I don't remember adding this in the previous commits. Will have a look into it.

**Comment by lucassmacedo** [comment]
i have the same problem

**Comment by wendellverli** [comment]
Can I upload PHOTOS from my desktop??

**Comment by orjanv** [comment]
same problem here too

**Comment by terkelg** [comment]
It's not possible to upload from desktop at the moment.
We are looking for maintainers of this project too.

**Comment by terkelg** [comment]
It's now possible to upload photos. We're going to add full support for this in the next few weeks.
