### ISSUE TITLE
About-page shows only error

### ISSUE THREAD

**Issue by theel0ja** [terkelg/ramme#104]
![image](https://cloud.githubusercontent.com/assets/5832930/24372903/333351dc-1338-11e7-80d4-61588e02ca22.png)
[Alt] -> Help -> About

            Ramme 3.0.3
            Electron 1.4.14
            linux x64 4.4.0-53-generic

**Comment by anatolinicolae** [comment]
Error due to a code migration from v2 to v3. Will fix for next release.

**Comment by Fincer** [comment]
I get exactly the same error message (same strings & numbers and so on). Ramme, v. 3.1.0.

**Comment by bil-elmoussaoui** [comment]
It's due that we were pointing to an icon that doesn't exists on a folder that doesn't exists neither; I've pushed a PR to fix it

**Comment by bil-elmoussaoui** [comment]
Fixed on master
