### ISSUE TITLE
Cache content offline

### ISSUE THREAD

**Issue by nedrichards** [terkelg/ramme#106]
If you launch the app with the computer offline you see a blank screen, it'd be great if the contents from the previous run were cached.

**Comment by terkelg** [comment]
It's currently just a wrapper around the instagram website.
I'm not sure what the possibilities are here. I'm a bit busy, but if you have time to look at this I'll love to accept a pull request on this 👍

**Comment by anatolinicolae** [comment]
It could be done if we switched to an API instead of working on the wrapper. The current state doesn't allow us to do this kind of caching mainly because we can't fetch new items on start and show the cached ones...

**Comment by nedrichards** [comment]
For sure! I was wondering about caching but that makes sense as to why it's not an 'easy hack'. I'll certainly have a think about 'you are offline' messaging as well.

**Comment by terkelg** [comment]
That could be a good solution. It should be easy to detect connection and display some sort of message.

**Comment by terkelg** [comment]
How's it going with this @nedrichards and @anatolinicolae? Otherwise I'll close this issue.

**Comment by anatolinicolae** [comment]
It requires a lil more code to get something like this done but there's no Instagram client that does it. Flume for macOS has a loading indicator which loads latest content and even Instagram for iOS has a blank screen after which new posts are loaded. We can do a similar thing to the indicator but caching posts is not a thing we can do with a web wrapper.

Yet, if anyone has it working, that's a great thing! Just send a PR 😃
