### ISSUE TITLE
Do not hardcode tray icon on Linux

### ISSUE THREAD

**Issue by theel0ja** [terkelg/ramme#108]
Tray icon is not themable on Linux.

**Comment by bil-elmoussaoui** [comment]
sadly, electron tray icons can not be themeable.. at least for now :) you can use Hardcode-Tray to achieve the same result :)

**Comment by terkelg** [comment]
I don't have linux and I can't test this myself. Let me know if you're up for this @anatolinicolae

**Comment by bil-elmoussaoui** [comment]
@terkelg This can be closed, as electron doesn't provide a solution for it

**Comment by terkelg** [comment]
Thanks for the help @bil-elmoussaoui - I appreciate that.
Yet another reason to consider if Linux should be supported #115.

**Comment by bil-elmoussaoui** [comment]
@terkleg Chrome does support Icon themes on Linux. But electron doesn't
