### ISSUE TITLE
Instagram "header bar" cuts off home icon(Linux:ElementaryOS-Freya[Ubuntu16.04])

### ISSUE THREAD

**Issue by DroWnThePoor** [terkelg/ramme#109]
![rammeissue](https://cloud.githubusercontent.com/assets/16339020/24583689/0e680978-1721-11e7-8512-3a8b342dbc00.png)
I hate making issues for this app, I know it's gotta be hard keeping up with an un-official version of one of the most popular cloud-apps on the net.

**Comment by anatolinicolae** [comment]
Don't worry dude, but it happens. In v3 we still kept the selectors of the first versions of the app so it is kinda expected since they were "static class" selectors which may change on new Instagram deploys.
Will release a new update soon fixing it 😉

**Comment by DroWnThePoor** [comment]
Thank you sir, you guys rock.

**Comment by terkelg** [comment]
I'll work on Ramme this week and take look at this.

**Comment by bil-elmoussaoui** [comment]
Fixed that on my local machine! A PR is coming 
![screenshot from 2017-05-24 21-39-09](https://cloud.githubusercontent.com/assets/7660997/26422277/78f3c670-40c9-11e7-8c72-fec9489959e9.png)

**Comment by bil-elmoussaoui** [comment]
This is now fixed
