### ISSUE TITLE
Sidebar glitch

### ISSUE THREAD

**Issue by muphli** [terkelg/ramme#110]
There's a glitch in the sidebar. Timeline-button and back-button overlap/are too close.
<img width="81" alt="ramme_sidebar" src="https://cloud.githubusercontent.com/assets/744156/24828360/66132cb8-1c5b-11e7-9aa8-6f2c3a838027.png">

            Ramme 3.0.3
            Electron 1.4.14
            darwin x64 16.5.0

**Comment by chocoelho** [comment]
See #109

**Comment by terkelg** [comment]
Thanks, duplicate of #109 and #113 . I'm going to work on Ramme this week and fix this.
