### ISSUE TITLE
[Consider] Remove linux support

### ISSUE THREAD

**Issue by terkelg** [terkelg/ramme#115]
Almost every open issue is linux related.
I don't have linux myself, and can't test or debug it. I'm looking for maintainers who can help with this. I don't have the time to look into this myself, and I therefore consider to remove linux support.

**Comment by aranajhonny** [comment]
I'll check the errors with linux. I do not think it is compatible with all desktop environments. I will try to make it work in the most used ones.

**Comment by Fincer** [comment]
Why don't you set up a virtual desktop environment (Lubuntu, Kubuntu?) on VirtualBox for testing purposes?

It would help a lot if the program were compiled with debug symbols or there would be step-by-step instructions how to do that. I already saw [an issue](https://github.com/terkelg/ramme/issues/97) for that but couldn't get the same files as an output than it's included in the precompiled deb package and didn't investigate it further. (I don't need fine-tuned instructions, very basic commands for how to get the same output is enough)

**Comment by terkelg** [comment]
Thanks for helping out @aranajhonny and @Fincer. I haven't had the time to setup the VM and look at it yet.

**Comment by DroWnThePoor** [comment]
Please do not cancel this for Linux, it's pretty popular. This is built on Electron right? What parts of the code have to be native to Linux?

**Comment by MichaelTunnell** [comment]
I haven't had the time to setup the VM and look at it yet.

Premade Virtual Machines for [Ubuntu](http://www.osboxes.org/ubuntu/) and [Ubuntu GNOME](http://www.osboxes.org/ubuntu-gnome/).

---------------

i don't understand what is Linux specific but if you were to end support for Linux then that means I will have to find an alternative.

**Comment by terkelg** [comment]
I just don't have the time to look into the bugs. I've been looking for people to help maintain, but without luck.

@DroWnThePoor there's just some issues with the layout, and yes, it's built in Electron.

**Comment by bil-elmoussaoui** [comment]
@terkelg I can help with testing/fixing bugs on Linux,; and also write some features if needed. Do you have a way to communicate with the rest of the team?

**Comment by terkelg** [comment]
Hi @bil-elmoussaoui thanks for helping out. You're more than welcome to join us on slack.
Let me know which email can use to invite you

**Comment by bil-elmoussaoui** [comment]
Bil[dot]elmoussaoui[at]gmail[dot]com
Can you remove this comment once it's done? Thanks

**Comment by jeffgoh** [comment]
Just downloaded the Linux version - will see if I can help in any meaningful way.

**Comment by terkelg** [comment]
Thanks folks. Nice to have some maintainers on board!

**Comment by bil-elmoussaoui** [comment]
I'm going to close this, as i'm going to take care of this, any help is more than welcome!
