### ISSUE TITLE
Possibility to upload video ? and png image ?

### ISSUE THREAD

**Issue by laurent-d** [terkelg/ramme#119]
Thanks for your amazing Work @terkelg !!!
Is it in the schedule the support of video  upload?
Cheers

**Comment by terkelg** [comment]
We can only do what Instagram themself allow. It's not possible at the moment, but thanks for the feature request and interest in Ramme. 👍

**Comment by d0od88** [comment]
PNG uploads do work, but for some reason the file picker doesn't allow you to 'see' them. It only shows .jpg and .jpeg files.

**Comment by bil-elmoussaoui** [comment]
Can you do that from the web site? If so, can you reopen a new issue about that and i will see how i can fix it :)
