### ISSUE TITLE
upload feature and 32bit version ?

### ISSUE THREAD

**Issue by mehkera** [terkelg/ramme#121]
Hi,
l love your app , i would love to have/test the upload feature but i'am running linux on a 32bit pc ,all latest versions where on 64bits !

So i'am very interested in 32bits deb version for linux ?

Thanks for your work.

**Comment by bil-elmoussaoui** [comment]
We do use electron-builder. I will see if it's possible to add 32bits packages too!

**Comment by alpvonkri** [comment]
Some of us would also like an RPM package, but additionally to that, most modern Linux distributions have dropped 32bit architecture, so in medium and long therm it will become obsolete.

**Comment by bil-elmoussaoui** [comment]
I will add an RPM package too =)

**Comment by bil-elmoussaoui** [comment]
@alpvonkri RPM package is now on master
