### ISSUE TITLE
ERROR while launching the app

### ISSUE THREAD

**Issue by acdcpow** [terkelg/ramme#124]
ramme 3.2.1 
WINDOWS10

ERROR : A JavaScript error occured in the main process
uncaucht exception:
typeError: Error processing argument at index 0, conversion failure from
at Object.exports.createtray
at App.
at emitTwo (events.js:111:20)
at App.emit (events.js.191:7)

**Comment by anatolinicolae** [comment]
Fixed in v3.2.2.
