### ISSUE TITLE
Huge gap between sidebar and feed

### ISSUE THREAD

**Issue by truckerboy** [terkelg/ramme#125]
In version 3.2.1, I see a huge vertical gap between the sidebar and feed. Screenshot is attached. The gap should be minimal.
![screenshot-20170527134828-551x508](https://cloud.githubusercontent.com/assets/23089829/26523335/94136e30-42e3-11e7-9c18-c42981e3d055.png)

**Comment by bil-elmoussaoui** [comment]
There was an attempt to fix this #114 but it seems that people who didn't have this issue have this one instead now

**Comment by anatolinicolae** [comment]
Fix #114, break #114. 😄

**Comment by alexsalex** [comment]
MacOS same issue

**Comment by bil-elmoussaoui** [comment]
Fixed
