### ISSUE TITLE
Text on top of first post (name of poster) gets cut off in default window

### ISSUE THREAD

**Issue by truckerboy** [terkelg/ramme#126]
The text on top of first post (name of poster of first post in feed) gets cut off in default window. It becomes visible only on maximizing Ramme. Changing window size while NOT maximized, does not fix the problem.
![screenshot-20170527135545-548x150](https://cloud.githubusercontent.com/assets/23089829/26523385/8435c142-42e4-11e7-92bf-b2e831850281.png)

**Comment by bil-elmoussaoui** [comment]
You shouldn't be able to maximize  the window :(

**Comment by fleamour** [comment]
I want full screen!?!

**Comment by anatolinicolae** [comment]
@fleamour say again, you don't seem pretty sure about that! 🤣

**Comment by fleamour** [comment]
Well deb installs Linux Mint 18.1 & fullsize maximise works. Tumbleweed KDE needs to be set through right clicking on window list then checking fullscreen .

**Comment by tushgup** [comment]
Yes, just noticed this error.

**Comment by bil-elmoussaoui** [comment]
Fixed
