### ISSUE TITLE
Gap between Sidebar and Feed does not change color whenswitching between dark or light mode

### ISSUE THREAD

**Issue by truckerboy** [terkelg/ramme#127]
The big gap between Sidebar and Feed does not switch color instantly when changing mode. It take a second and then auto-refreshes and then manages to change its color to the selected theme.
Same result when clicking on the menu or using the keyboard shortcut (ctrl+d) to switch theme.

**Comment by bil-elmoussaoui** [comment]
I've added the auto refresh because i couldn't manage to get the correct CSS rule to fix it.
@anatolinicolae Can you give it a try?

**Comment by octacian** [comment]
Fixed by #193. The gap was originally for the sidebar, however, at this point, we're just using the default navigation bar at the bottom so it has been removed. Closing this issue for now.
