### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by alpvonkri** [terkelg/ramme#128]
It's great that an RPM package was added, sadly it won't install (in some unattended scenarios) because the libnotify and libappindicator dependencies are not provided by that names in all distributions, like for example, in openSUSE they are named libnotify4 and libappindicator1, so, maybe building the package with no dependencies stated or they being in the Suggests or Recommends sections.
For now, I'll continue to make my own RPM package.

**Comment by bil-elmoussaoui** [comment]
We don't set any dependency from our side...

**Comment by anatolinicolae** [comment]
Give it a try mate, the app itself will definitely work. The only thing you'll miss will be the tray icon. Let us know if it works or not :)

**Comment by alpvonkri** [comment]
Don't know how you're building the RPM, but generally there must be an SPEC file, in that file you specify dependencies and so, like for example my SPEC to build the RAMME RPM contains this (for openSUSE)

> Requires: gconf2, libnotify4, libappindicator1, libXtst6, mozilla-nss
> AutoReqProv: no

Requires, are the dependencies needed to run it (this were based in the DEB package), AutoReqProv, specifies if the rpm building process will auto detect dependencies or not, I set it in NO as I do it manually, and usually works better.

I'll test the version 3.2.2 once my package is complete and share the results with you guys.

KEEP UP THE GOOD WORK. :)

**Comment by bil-elmoussaoui** [comment]
Do you have any idea of the equivalent of those packages on Fedora?

**Comment by alpvonkri** [comment]
@bil-elmoussaoui I don't, but must be something similar, don't have a Fedora VM to verify it now.

**Comment by bil-elmoussaoui** [comment]
I will take a look and see if i can fix it. As i don't use Fedora or anything like that (Arch forever guy)

**Comment by alpvonkri** [comment]
By the way, 3.2.2 works with tray icon, the only thing is that when opening the app always show a tooltip in the Home button.
![screenshot_20170527_155019](https://cloud.githubusercontent.com/assets/104341/26524301/6885be38-42f4-11e7-9259-1a7bcc7c0361.png)

**Comment by alpvonkri** [comment]
> I will take a look and see if i can fix it. As i don't use Fedora or anything like that (Arch forever guy)
@bil-elmoussaoui if the RPM doesn't contain preset dependencies, it will work in every distribution, maybe only specify in the README that you need to verify for them to be installed to use Ramme.

**Comment by alpvonkri** [comment]
By the way, it could be helpful to include the app version somewhere in it, as it is needed to know it and check if you have the latest one.

**Comment by bil-elmoussaoui** [comment]
It will take some time to get this fixed as i'm super busy with finals, but i will get it fixed for the next version (i hope)
