### ISSUE TITLE
App Image Not Integrating With KDE

### ISSUE THREAD

**Issue by fleamour** [terkelg/ramme#131]
openSUSE Tumbleweed KDE App Image not integrate with system. Not showing in search or being indexed among programs. Have to launch from executible each time.

**Comment by bil-elmoussaoui** [comment]
Normally when you open a AppImage application it should ask you either you want to create a desktop file or not.
Anyway, we're just using electron-builder to create Appimages which seems to work just fine for me...If Appimages doesn't work correctly on your system then it's an upstream bug for AppImage devs.
Can't do anything about it. Closing
