### ISSUE TITLE
App Image Not Toggle Full screen

### ISSUE THREAD

**Issue by fleamour** [terkelg/ramme#132]
KDE openSUSE Tumbleweed App Image not toggle full screen.

**Comment by bil-elmoussaoui** [comment]
@anatolinicolae @terkelg Should we keep it this way or not ? as in some linux distros, using a resizable: false for the BrowserWindow object doesn't change anything.
What we can use instead is maybe, forcing the frame to false on linux & windows and add a beautiful close button on the window

**Comment by terkelg** [comment]
Sounds good to me 👍

**Comment by bil-elmoussaoui** [comment]
This by design, we don't want the user to have a full screen window for seeing his feed on instagram; But we will likely implement a zoom on click feature (in the future)
