### ISSUE TITLE
no upload button on latest archlinux release

### ISSUE THREAD

**Issue by tchncs** [terkelg/ramme#136]
Hi, i just installed the latest `.pacman` package.
There is no photoupload button to see.

Currently downloading the AUR package which is older... .

Edit: same with the AUR package.

**Comment by bil-elmoussaoui** [comment]
When you use the instagram website, do you have an upload button?

**Comment by bil-elmoussaoui** [comment]
As I've answered on another issue like this one. Instagram web app didn't deploy this feature worldwide yet.
