### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by terkelg** [terkelg/ramme#14]
Let users know about new releases.

**Comment by yeskunall** [comment]
Hi @terkelg! Are you currently working on this feature or have you kept it on hold in favor of other more requested features?

**Comment by terkelg** [comment]
Hi! I'm not working on this or any other features at the moment. I'm too busy with work

**Comment by yeskunall** [comment]
Dropping this here, just in case anyone wants to work on this feature independently.

Auto-updating `Electron` apps is handled by `Squirrel`, a separate framework in itself. It currently only supports `Mac` and `Windows`. There's no way to auto-update apps on `Linux`. Not that I'm aware of.

The [autoUpdater](http://electron.atom.io/docs/api/auto-updater/) module might also be a good place to start.

**Comment by vintagesucks** [comment]
> Let users know about new releases.

See #33
