### ISSUE TITLE
ubuntu mate---  look at this  gif animated.  

### ISSUE THREAD

**Issue by Jkings777** [terkelg/ramme#140]
[https://media.giphy.com/media/3ohzdK31uMYdVhpGNi/giphy.gif](url) 

[https://media.giphy.com/media/xUPGcylf5xMa7sbbMI/giphy.gif](url)

i don't know how to explain, but as you can see this gif animated.

**Comment by bil-elmoussaoui** [comment]
Already reported and will be fixed on the next release .
See #125
