### ISSUE TITLE
Crashes system on Elementary OS 0.4-Loki

### ISSUE THREAD

**Issue by DroWnThePoor** [terkelg/ramme#141]
Very strange, but it crashes my system when I run it by clicking on the icon.
However, when running it by typing ramme into terminal it launches as expected.

**Comment by bil-elmoussaoui** [comment]
Well, i can't do anything about it.. As the desktop file all it does is executing the same command...It must be something else broken on your system that crash your system.
As i'm using elementary OS on a virtual machine and everything works fine for me. If you can still reproduce that on a freshly installed elementary system reopen this
Closing
