### ISSUE TITLE
Linux issue with resizing and properly centering the feed/etc.

### ISSUE THREAD

**Issue by Cursewords** [terkelg/ramme#144]
On Linux (Xubuntu fresh install) the app doesn't properly display. Feed window and pictures are pushed into the right which results in truncating about 20% of the window elements.

**Comment by pedrofleck** [comment]
I confirm to have this issue too, and the upper bar also cuts a little the feed.

**Comment by bil-elmoussaoui** [comment]
Duplicate of #125
