### ISSUE TITLE
no upload button on fedora 25

### ISSUE THREAD

**Issue by lorenzadam** [terkelg/ramme#147]
Hello, i just installed the latest .rpm package.
but no photoupload button there.

**Comment by bil-elmoussaoui** [comment]
Are you able to see the upload button if you use the instagram website?

**Comment by bil-elmoussaoui** [comment]
Closing as this must be an instagram issue (Maybe the upload button from Instagram web app hasn't been deployed world wide)

**Comment by lorenzadam** [comment]
Yes i dont see the upload button when using instagram website
