### ISSUE TITLE
Profile fails to update after creating or deleting post

### ISSUE THREAD

**Issue by FalseAscension** [terkelg/ramme#150]
The tile is pretty much self explanatory.
I have the latest version of Ramme installed (updated today), however when I upload an image, caption it, etc, the post is uploaded fine, however it does not appear on my profile when i look at it with Ramme.

**Comment by bil-elmoussaoui** [comment]
@anatolinicolae What do you think about this issue? We might need to add a refresh of the page after adding a new image

**Comment by anatolinicolae** [comment]
Check current URL and force `cmd+R/ctrl+R` on change I guess. Have to look again in the app structure and I'll let you know 😉
