### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by nouh01** [terkelg/ramme#151]
Uncaught Exception:
TypeError: Cannot read property 'name' of undefined
    at getConf (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:13:73)
    at firstRun (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:25:13)
    at Object.exports.init (/opt/Ramme/resources/app.asar/dist/main/analytics.js:1:388)
    at App.<anonymous> (/opt/Ramme/resources/app.asar/dist/main/index.js:9:36)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)

**Comment by compuguy** [comment]
Having a similar issue as well:

> Uncaught Exception:
> TypeError: Cannot read property 'name' of undefined
>     at getConf (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:13:73)
>     at firstRun (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:25:13)
>     at Object.exports.init (/opt/Ramme/resources/app.asar/dist/main/analytics.js:1:388)
>     at App.<anonymous> (/opt/Ramme/resources/app.asar/dist/main/index.js:9:36)
>     at emitTwo (events.js:111:20)
>     at App.emit (events.js:194:7)

**Comment by grande90210** [comment]
This one happening when another instance of the Ramme already running.

**Comment by drigio** [comment]
Should have an option asking whether i want the app to keep running in background or totally end the process when i exit the instance.

**Comment by ummasdf** [comment]
This is now happening to me as well on Windows 10 64 bit, Intel i3-2330 with integrated graphics.

https://gyazo.com/1504e7df65bab931ba6ec3921d774e24

**Comment by Hadeeskyu** [comment]
> Having a similar issue as well:
> 
> > Uncaught Exception:
> > TypeError: Cannot read property 'name' of undefined
> > at getConf (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:13:73)
> > at firstRun (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:25:13)
> > at Object.exports.init (/opt/Ramme/resources/app.asar/dist/main/analytics.js:1:388)
> > at App. (/opt/Ramme/resources/app.asar/dist/main/index.js:9:36)
> > at emitTwo (events.js:111:20)
> > at App.emit (events.js:194:7)
> 
> 3.2.2. 3.2.1, 3.2.0 affected (Ubuntu 17.04, AppImage and deb).
> 
> Edit: Clean out the config for ramme, seems to resolve the issue.

How to clean the config?
