### ISSUE TITLE
Side margin issue and toolbar overlaps

### ISSUE THREAD

**Issue by knightazura** [terkelg/ramme#152]
There additional margin (or padding?) on left and toolbar overlaps the body on all layouts.
Sorry for my bad english .

![screen shot 2017-06-17 at 12 12 30 am](https://user-images.githubusercontent.com/7548569/27237051-c4c36dd2-52f1-11e7-8837-8e621609ed7e.png)

Ramme 3.2.2
Electron 1.7.2
darwin x64 16.6.0
macOS 10.12.5

**Comment by bil-elmoussaoui** [comment]
already fixed on master
