### ISSUE TITLE
Main feed not refreshing

### ISSUE THREAD

**Issue by multispeed** [terkelg/ramme#153]
The main feed/storyline is not refreshing in Ramme 3.2.2

![image](https://user-images.githubusercontent.com/22557639/27323647-8e5aa112-55a2-11e7-9330-92f68169371c.png)

**Comment by zeitan** [comment]
Same here, failing in linux (elementary os loki)

**Comment by YodaOz** [comment]
same. manjaro kde

**Comment by vladcraft** [comment]
main feed refreshing only manual ctrl+R. kde

**Comment by Madkita** [comment]
@vladcraft  
are you using the global menu on KDE?

**Comment by vladcraft** [comment]
@Madkita Yes.

**Comment by Madkita** [comment]
ok i am too but when i click on it the shell just restarts 
am not neon

**Comment by sreeramp96** [comment]
![Screenshot (141)](https://user-images.githubusercontent.com/16064120/56334605-9d268400-61b6-11e9-84eb-b031c7218e35.png)
while using cntrl + R it shows this and when i click ok it then refreshes and works fine but everytime i refresh this error comes
