### ISSUE TITLE
Problems with the interface

### ISSUE THREAD

**Issue by Archakov06** [terkelg/ramme#154]
The application is just wonderful! However, the application interface for some reason curve

MacBook Pro (Retina, 13-inch, Mid 2014) | macOS Siera 10.12.3 (16D32)

![](http://savepic.net/9414471.png)

Such in all sections

**Comment by bil-elmoussaoui** [comment]
Already fixed on master. please use the search before reporting any issue. it was reported like 10 times...

**Comment by Archakov06** [comment]
Good. Excuse me.
