### ISSUE TITLE
Home Header Not Fully Displayed

### ISSUE THREAD

**Issue by mmarquardt** [terkelg/ramme#155]
On Windows 10 my home page header, photo and username and statistics, information is/are not fully displayed and is/are cut off at the top.  Not too well said, but hope the message is clear.  Thanks.

**Comment by bil-elmoussaoui** [comment]
This issue was reported like 10 times. Please guys, use the search future on Github and search for issues before reporting the same thing again and again. It's fixed on master (next release)
