### ISSUE TITLE
blocking of feed by Instagram text

### ISSUE THREAD

**Issue by AkSachin** [terkelg/ramme#159]
On macOS, in home tab the Instagram feed is getting blocked by "Instagram" text.
![screen shot 2017-06-24 at 1 56 38 am](https://user-images.githubusercontent.com/11594075/27499336-e8934b80-5880-11e7-9bd2-c5f91d2b66ce.png)

This is the same case with search tab, some portion of the top feed is covered with search textbox and in profile tab, some portion is covered by text "Profile".
![screen shot 2017-06-24 at 1 57 01 am](https://user-images.githubusercontent.com/11594075/27499630-5b3576bc-5882-11e7-8c1a-a02c80e523b6.png)

![screen shot 2017-06-24 at 1 57 22 am](https://user-images.githubusercontent.com/11594075/27499517-d3640fdc-5881-11e7-8746-eba09cba4be4.png)

And in the Activity tab as well :
![screen shot 2017-06-24 at 1 57 12 am](https://user-images.githubusercontent.com/11594075/27499512-c85a214e-5881-11e7-8a5a-a905be34580c.png)

            -

            Ramme 3.2.2
            Electron 1.7.2
            darwin x64 16.6.0

**Comment by troe** [comment]
The same and on the Linux Kubuntu 16.04, version Ramme 3.2.2

![ramme 2](https://user-images.githubusercontent.com/1324558/27505922-40331526-58ce-11e7-909d-05de586fe124.png)

**Comment by bil-elmoussaoui** [comment]
Already fixed on master. I will fix some other issues and create a new release soon :)
