### ISSUE TITLE
i use ramme 3 2 2, plis fix this problem in Dark circles

### ISSUE THREAD

**Issue by rahmatdani** [terkelg/ramme#160]
![bug1](https://user-images.githubusercontent.com/29314308/27661554-453e28e0-5c8d-11e7-8b7f-3915b18b33f4.png)

**Comment by bil-elmoussaoui** [comment]
Duplicate

**Comment by rahmatdani** [comment]
plis solved

**Comment by bil-elmoussaoui** [comment]
Already fixed on master

**Comment by rahmatdani** [comment]
I do not understand, What should I do for normal apps?
i use google translate
