### ISSUE TITLE
Direct Messaging?

### ISSUE THREAD

**Issue by mrfizzl3** [terkelg/ramme#161]
I use Ramme as an alternative to the Instagram Windows app that I used a lot for personal messaging. Is there any plans for putting the Instagram Direct feature in Ramme? Thanks!

**Comment by Dvhinds37** [comment]
I am having this issue as well. I am running Fedora 26 and am considering using the windows version under wine to see if it will run that way. Anyone on the development side have an idea of a possible solution?  I am wary to use wine as I am having other issues with another app in wine.

Thanks in advance for any advice or suggestions.
D

**Comment by rielinux** [comment]
Yes please, provide the direct messaging on Ramme.... :)

**Comment by roccomuso** [comment]
+1 thanks!
