### ISSUE TITLE
Window is too small to fit feed

### ISSUE THREAD

**Issue by sebastiansondergaard** [terkelg/ramme#162]
The window is too small to show the feed as you can see here: https://puu.sh/wD06l/c12014aeff.png

Would be nice if that could be fixed ;-)

**Comment by vladcraft** [comment]
I confirm. Too such problem. Last kubuntu.

**Comment by denisinla** [comment]
@vladcraft @sebastiansondergaard downgraded to 3.2.0(Issue started in 3.2.1) fixed the issue for me. Hopefully 3.2.3 will have this issue fixed.

**Comment by bil-elmoussaoui** [comment]
This is a duplicate and already fixed on master. I've just released a new version right now.
