### ISSUE TITLE
Plan posts

### ISSUE THREAD

**Issue by vladcraft** [terkelg/ramme#163]
The program is able to post. Is it possible to increase functionality, plan posts, like in "planoly" or in "buffer". So that you can plan your posts and sort not yet published.

**Comment by bil-elmoussaoui** [comment]
What do you mean by that?

**Comment by anatolinicolae** [comment]
@bil-elmoussaoui I think he's talking about scheduling posts' date and time.
@vladcraft No, this is not possible since this is a web wrapper and we're not using any private API integration to post.
