### ISSUE TITLE
Gnome-shell, the top part of ramme is hidden by window bar / title bar

### ISSUE THREAD

**Issue by sonejizrelax** [terkelg/ramme#164]
![image](https://user-images.githubusercontent.com/12625848/28440605-dd6ce97c-6d9e-11e7-823f-135049037596.png)
as seen here, i cannot see the user. This is particularly annoying in the activity tab. 

Any help would be appreciated despite the fact i know this is sort of not a ramme bug

**Comment by bil-elmoussaoui** [comment]
This is a duplicate and already fixed on master. I've just released a new version right now.
