### ISSUE TITLE
Add emoji support.

### ISSUE THREAD

**Issue by vladcraft** [terkelg/ramme#165]
Lacks both the display and writing emoji when commenting.

The last kubuntu.

**Comment by bil-elmoussaoui** [comment]
The display of emojis is must be a missing font on your system.

**Comment by bil-elmoussaoui** [comment]
But i agree that we should implement an easy way to add emojis

**Comment by jsejcksn** [comment]
Maybe [emoji-picker](https://github.com/OneSignal/emoji-picker) will be useful for this? It has a jquery dependency.
