### ISSUE TITLE
Side menu on windows problem version 3.2.3 .exe

### ISSUE THREAD

**Issue by Angelk90** [terkelg/ramme#166]
On windows, the side menu does not work properly.
See attached picture:

![eletcotod](https://user-images.githubusercontent.com/20476002/28499808-c41d21a4-6fbe-11e7-86e1-acdf27b6d25d.png)

Windows 8.1

**Comment by bil-elmoussaoui** [comment]
The issue is not anymore a problem as Instagram has changed the position of the sidebar to the bottom so it's another issue to track https://github.com/terkelg/ramme/issues/151
