### ISSUE TITLE
windows problem version 3.2.3

### ISSUE THREAD

**Issue by Angelk90** [terkelg/ramme#167]
I downloaded the package: https://github.com/terkelg/ramme/archive/v3.2.3.zip
I installed the components: npm install
On windows, the side menu does not work properly, you can not see it.
The posts, they look strangely.
See attached picture:

![eletcotod](https://user-images.githubusercontent.com/20476002/28499872-c9ed5f3a-6fbf-11e7-80ca-fa27187fa77f.png)

Windows 8.1

**Comment by anatolinicolae** [comment]
Why didn't you download the .exe file? No need to install modules every time, but dunno, choices.
Regarding the issue you're having, can you try clearing the cache? Right click the tray icon and click Clear cache, then let us know!

**Comment by Angelk90** [comment]
I also downloaded the .exe version, if I had read the other two posts, in which I notice other bugs, you would have understood.
Anyway, I tried to empty the cache but it does not solve anything.
Try it yourself:
If you download the package: https://github.com/terkelg/ramme/archive/v3.2.3.zip
Install components, place a screen, to see what you see.
Let us know.

**Comment by bil-elmoussaoui** [comment]
The sidebar changed it's position on a new update upstream (Instagram) so this issue is no more valid. And we should track & fix this one instead 
https://github.com/terkelg/ramme/issues/176
