### ISSUE TITLE
Dark mode: dark elements on dark background, very hard to see

### ISSUE THREAD

**Issue by sg6** [terkelg/ramme#171]
![image](https://user-images.githubusercontent.com/10222288/28707908-77c9eb60-737a-11e7-9cf3-eaf9271311f1.png)

On dark mode, I cannot see the <3 symbol and the count of the likes.

Minor CSS bug !

**Comment by octacian** [comment]
It seems to me as though this was fixed a while ago, it doesn't occur now that I know of. Can this issue be closed?

**Comment by bil-elmoussaoui** [comment]
Thanks for the help @octacian
