### ISSUE TITLE
Window goes blank (white) when prompting to add phone number to account

### ISSUE THREAD

**Issue by StarlordSTRX** [terkelg/ramme#174]
I know for a fact that instagram is prompting me for a phone number over the app (and i haven't given them one). When i sign in via Ramme I see the 'Add phone number' page for a millisecond before the whole page goes white. Restarting the app does not solve this issue. 

Version 3.2.3 on Windows 10

**Comment by octacian** [comment]
This one is slightly harder to reproduce... @StarlordSTRX do you think you could provide a short screen recording or GIF of the issue?

I notice that I can change the phone number on the edit profile page, but I was unaware of the ability to modify this elsewhere.

**Comment by StarlordSTRX** [comment]
IG probably got suspicious of my login attempts and is forcing me to give phone number to login. I had a hard time actually spotting the page this time (but i've clearly seen it before on ramme as well as on my phone). Verified that this indeed is the issue by logging in with another account and it worked fine.

Hope the gif helps even if it doesn't show much.

![the_problem](https://user-images.githubusercontent.com/6453969/29848401-995db0c6-8d20-11e7-9231-bfe8924acaaf.gif)
