### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by Blacksuan19** [terkelg/ramme#175]
I don't know what is wrong but in KDE neon with plasma 5.10.4 its using more than 100% of the CPU 
tell me if you need any type of logs 

![screenshot_20170806_171310](https://user-images.githubusercontent.com/10248473/29002000-bae6777c-7aca-11e7-8cf1-6c6d1d196e2e.png)

**Comment by bil-elmoussaoui** [comment]
I don't think we can do too much about this. As the whole application is just a wrapper for the Instagram website. But we will see if there's something that runs all the time :)

**Comment by TheSamSmith** [comment]
@Madkita I think that it means its using 100% of the CPU its allocated. I think you'll find that if you close Chrome your CPU usage will decrease significantly and therefore wont look as bad on the graphs. Even with Ramme running your CPU is only on about 47% across the cores.
