### ISSUE TITLE
Menu bar is fixed to bottom of view

### ISSUE THREAD

**Issue by danieldafoe** [terkelg/ramme#178]
I'm not sure if this was changed in a newer version, but the screenshots in the repo still showed the menu being on the left, so I just want to ensure that it being on the bottom for me is the desired behaviour.

I **am** running macOS High Sierra v10.13 Beta 4, so I just figured that was the issue, but please confirm where it should be.

**Comment by ussserrr** [comment]
Same at El Capitan (Air 13). Also Dark theme isn't work for me.
![ramme](https://user-images.githubusercontent.com/20915411/29233568-59b7f08c-7efa-11e7-82a3-52b273f5ff2b.png)
![ramme_dark_theme](https://user-images.githubusercontent.com/20915411/29233569-5a4bd7c0-7efa-11e7-82b1-c118b723eeb1.png)

**Comment by yarik2720** [comment]
Confirmed on Windows 8.1

**Comment by bil-elmoussaoui** [comment]
Guys, don't report duplicate issues please. 
https://github.com/terkelg/ramme/issues/176
