### ISSUE TITLE
Overlapping app controls and UI elements

### ISSUE THREAD

**Issue by brandonmcconnell** [terkelg/ramme#182]
The close, minus, and maximize buttons overlap some of the app's UI elements
![image](https://user-images.githubusercontent.com/5913254/29304101-4f0e2e82-815f-11e7-894f-12695724d9b9.png)

**Comment by bil-elmoussaoui** [comment]
Is that on macOS?

**Comment by FradSer** [comment]
![2017-08-24 14 09 46](https://user-images.githubusercontent.com/1439628/29651953-dbefb280-88d5-11e7-8993-3bd27cde96d5.png)
Look different, maybe the same issue.

**Comment by FradSer** [comment]
@bil-elmoussaoui I think it is on macOS, so does mine.

**Comment by CreativeKoen** [comment]
I'm on windows and I have the same layout. I would love to have the same layout as shown in the readme. 
![image](https://user-images.githubusercontent.com/10489237/30243150-e9ae52de-95a3-11e7-96af-2f71bfb730ce.png)

**Comment by konstantinkobs** [comment]
This is the layout on my computer (macOS).

![screen shot 2017-09-15 at 18 59 41](https://user-images.githubusercontent.com/4562885/30494373-165ab342-9a48-11e7-8d4b-6c839abe7f21.png)
