### ISSUE TITLE
Can not logout

### ISSUE THREAD

**Issue by onezetty** [terkelg/ramme#198]
I can not logout, there is no menu, and if I delete the App, the config account still remains. I using Ubuntu 16.04 Unity.

**Comment by octacian** [comment]
Are you sure you checked in the right place? Last time I tried, it worked just fine. Just to confirm, the log out button can be found by going to your profile and clicking the "Settings" gear in the top-right corner.

**Comment by monkeyevil** [comment]
I'm having the same issue, settings gear is missing. I'm on 3.2.3
![image](https://user-images.githubusercontent.com/31444241/29825320-111829cc-8ca2-11e7-8c9a-46af7b029f41.png)

**Comment by onezetty** [comment]
Yep!, no logout menu.   

![screenshot_17-08-29_09-12-26](https://user-images.githubusercontent.com/4399989/29825514-4a7ddce6-8c9a-11e7-86f2-b9a6bbed5602.png)

**Comment by wilnarvaez** [comment]
I have the same problem, I use windows 10.

**Comment by dimitrimarinho** [comment]
I have the same problem. I'm waiting for the developers fix this problems or help us to solve this.

**Comment by unhammer** [comment]
Does 
```
cd ~/.config
rm -rf Ramme
```
at least work?

**Comment by anatolinicolae** [comment]
Force log out by clicking Logout from the tray icon or from the menu, will be available in the next release :wink:

**Comment by NabiKAZ** [comment]
I don't understand for logout from ramme in the win10 and I can not find any `.config` folder.

**Comment by AbhishekGangwar13** [comment]
I can't logout & switch account on Ramme

**Comment by lucas-wade** [comment]
still cant logout. i cant see any option to logout in the menu bar? i am on linux running gnome

**Comment by 1whatleytay** [comment]
Hehe... Since I was on mac, my config folder was hiding in "~/Library/Application Support/Ramme/"
`rm -rf "~/Library/Application Support/Ramme/"`
The above worked for me.

**Comment by thisrock** [comment]
just delete and extract last state

**Comment by dc0d** [comment]
Fixed yet? (running it using `yarn dev` and just logged out from the page inside. Now the app does not let me logout - `rm -rf ~/.config/Ramme` has no effect. Below is the error that is constantly happening).

```
Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at <anonymous>:1:481
    at EventEmitter.electron.ipcRenderer.on (/home/user/.../ramme/node_modules/electron/dist/resources/electron.asar/renderer…:52)
    at emitMany (events.js:146)
    at EventEmitter.emit (events.js:223)
```
