### ISSUE TITLE
Is it possible to post images?

### ISSUE THREAD

**Issue by appernetic** [terkelg/ramme#2]

**Comment by amitmerchant1990** [comment]
No. I don't think so Instagram will ever allow this.

**Comment by badcat** [comment]
It's listed on the Roadmap for version 2.0, no?

**Comment by gingerbeardman** [comment]
@badcat it was added to the roadmap before people alerted the developer that there is no approved or official way to do it. Instagram actively close down any app that uses their private methods.

**Comment by terkelg** [comment]
@gingerbeardman and @amitmerchant1990 are right. I won't add this at the moment. Instagram won't allow me to hijack user sessions and use the private API.
