### ISSUE TITLE
ramme blank screen in linux

### ISSUE THREAD

**Issue by ezequielmurga** [terkelg/ramme#200]
I have a Linux ubuntu 17.04 64 bits, with gnome. I download the latest version (3.2.3), it opens but only shows a blank screen.
![captura de pantalla de 2017-09-05 10-44-54](https://user-images.githubusercontent.com/31659164/30064161-4db65950-9227-11e7-9731-7dcccd9dbc84.png)
# #

**Comment by anatolinicolae** [comment]
Are you sure about the issue? Have you tried closing and re-opening it againa? :thinking:

**Comment by ezequielmurga** [comment]
Yes, I also reset the computer, but still the same

**Comment by Chathula** [comment]
Can you run  using terminal too see the errorsm?

**Comment by llajournade** [comment]
I have the same error using Fedora 28, and there is error in console :
`[nobod@localhost ~]$ ramme
Gtk-Message: 22:57:19.117: Failed to load module "pk-gtk-module"
Gtk-Message: 22:57:19.117: Failed to load module "canberra-gtk-module"
<memory>:1: Invalid color constant '##d3d3d3'
Gtk-Message: 22:57:19.624: (for origin information, set GTK_DEBUG): failed to retrieve property `ChromeGtkFrame::frame-color' of type `GdkColor' from rc file value ""##d3d3d3"" of type `gchararray'
`

**Comment by octacian** [comment]
Wait, why is Ramme even relying on GTK at all? It's built with Electron after all. Or does Electron depend on GTK? From what I see on Google, it seems that way, although it makes no sense to me. Could you try Ctrl+Shift+I (developer tools), click `Console`, and paste any errors? The latest release might have it disabled... I'm not sure though.
