### ISSUE TITLE
Ramme flatpak?

### ISSUE THREAD

**Issue by LeandroStanger** [terkelg/ramme#201]

**Comment by anatolinicolae** [comment]
Nice alternative to Snapcraft. We'll definitely have a look at it!

**Comment by bil-elmoussaoui** [comment]
@anatolinicolae I think the best is to wait until the latest version of electron is shipped so we can build the flatpak package using flathub (the online builder tool of flatpak)

**Comment by LeandroStanger** [comment]
How is progress for a flapak version going?

**Comment by leandromqrs** [comment]
News for a flatpak version?
