### ISSUE TITLE
Add "Back" Button

### ISSUE THREAD

**Issue by sgnd** [terkelg/ramme#203]
Please add a "back" feature, because after clicking a picture or video. can not go back to previous location.

**Comment by monk10101** [comment]
yes, please add a "back" feature.  or a keyboard shortcut that functions.
thanks.

**Comment by NabiKAZ** [comment]
can swipe right be like app

**Comment by lex111** [comment]
@anatolinicolae I would like to do, so I need to implement?

**Comment by anatolinicolae** [comment]
@lex111 basically yes, fetch the repo, implement and create a PR. We'll have a look and merge if it works fine! 😉

**Comment by samnegri** [comment]
Are you guys active? Should I make a PR for this?

**Comment by SammyIsra** [comment]
@samnegri I'm sure a PR would be appreciated!

**Comment by anatolinicolae** [comment]
@samnegri Yea, you can do it for v3. Will merge even though v4 rewrite already had it planned and implemented.
