### ISSUE TITLE
shows "Open in app" / "app store" links

### ISSUE THREAD

**Issue by unhammer** [terkelg/ramme#204]
![ramme](https://user-images.githubusercontent.com/56868/30288873-834b3524-972a-11e7-8cc3-4255011d8bf7.png)

not the best first impression ;)

**Comment by ghosh** [comment]
I can give this a go. It should be possible to hide it using css

**Comment by octacian** [comment]
This has long since been fixed in the latest master, and still is when I checked today. Just waiting for the new release. @terkelg BTW, @anatolinicolae fixed the crash on macOS.

**Comment by terkelg** [comment]
Awesome, I'll make a release then. Nice job @octacian and @anatolinicolae

**Comment by octacian** [comment]
@terkelg Before the new release though, I noticed there's an issue with dark mode and IG stories. That still ought to be fixed, can't do it for a few hours though.

**Comment by octacian** [comment]
@terkelg FYI, everything that needed to be fixed has been now.
