### ISSUE TITLE
most keyboard shortcuts don't work

### ISSUE THREAD

**Issue by monk10101** [terkelg/ramme#208]
the only shortcut that works is the refresh function. the dark mode only comes dark momentarly.
and no back feature.
running on linux mint 17.3 and ramme 3.2.3

**Comment by octacian** [comment]
These issues have been fixed in the latest master, but we haven't been able to make a new release yet because there is a bug on macOS that I haven't been able to fix yet.

**Comment by sina-mansour** [comment]
I'm running 3.2.5 on Ubuntu 18.04 and the shortcuts aren't working. any news on a fix?
