### ISSUE TITLE
Ramme Doesn't Close properly (Ubuntu/Linux)

### ISSUE THREAD

**Issue by jasiralavi** [terkelg/ramme#210]
I've installed Ramme (ver 3.2.3) on my Ubuntu 16.10.

The application doesn't close properly when I close the window (or even if I close using the menu option Window > Close option). I noticed this when I closed the window while a video with sound was playing. Although the window disappeared, the sound kept looping in background. I had to then kill the 'ramme' process from System Monitor to stop the sound and close the application.

I hope you will also release the fix for the layout and shortcut issues.

thanks for the wonderful app

**Comment by octacian** [comment]
39fdb07f5fd72e5798eec0205c01173654266386 and 89bc86807623460049c1faf7c6a653066640fd6e

Will be in next release. Closing issue for now.
