### ISSUE TITLE
Ramme dark mode is not working.

### ISSUE THREAD

**Issue by Vetronus** [terkelg/ramme#213]
When I click on the **Toggle Dark** mode button in the menu, ramme reloads with the default white skin.

I have uploaded a zip while which contains the video of 7 seconds. It shows exactly what is happening when I am trying to use **Dark Mode** option.

OS : macOS High Sierra
Device : Macbook Air
Ramme Version : 3.2.3
[DarkMode Bug.zip](https://github.com/terkelg/ramme/files/1366627/DarkMode.Bug.zip)

**Comment by as3mbus** [comment]
this problem happen to me too. 
OS : Ubuntu 16.04
Ramme Version : 3.2.3

**Comment by presianbg** [comment]
Same here - Arch
