### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by MichaelGatesDev** [terkelg/ramme#215]
I'm surprised the readme is lacking build instructions for this. I've cloned the repo and tried following the steps [here](https://github.com/terkelg/ramme/issues/97) but end up with [this](https://i.imgur.com/OzqEaI3.jpg) error.

It's looking for the CSS file in `src` instead of in `dist` and I have no idea why.

**Comment by anatolinicolae** [comment]
Totally fine build. There's an error I guess that you can find by running `yarn test` or `npm run test` 🤔

**Comment by MichaelGatesDev** [comment]
The tests run well.. I wonder why it's giving me issues. Using the distribution from the 'releases' page of this repository works fine for me..

**Comment by anatolinicolae** [comment]
Fixed that for you. Give it a pull mate!

**Comment by MichaelGatesDev** [comment]
Works now! Thank!
