### ISSUE TITLE
Facebook OAuth doesn't Work

### ISSUE THREAD

**Issue by chen8160** [terkelg/ramme#224]
Here is the link I got when trying to login with Facebook:

> https://www.facebook.com/v2.2/dialog/oauth?channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FhsBwMj6iLmk.js%3Fversion%3D42%23cb%3Df1d59cf6cb8ddbc%26domain%3Dwww.instagram.com%26origin%3Dhttps%253A%252F%252Fwww.instagram.com%252Ff1e785ccc1b029c%26relation%3Dopener&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FhsBwMj6iLmk.js%3Fversion%3D42%23cb%3Df3ad6a06654cdec%26domain%3Dwww.instagram.com%26origin%3Dhttps%253A%252F%252Fwww.instagram.com%252Ff1e785ccc1b029c%26relation%3Dopener%26frame%3Df2fcec483b825fc&scope=public_profile%2Cemail&response_type=token%2Csigned_request&domain=www.instagram.com&origin=2&client_id=124024574287414&sdk=joey&_rdr

But it loads up an empty page and I still can't login to the app.

**Comment by chen8160** [comment]
I did a little bit research online, looks like facebook dropped support of OAuth v2.2. 
[Reference on StackOverflow](https://stackoverflow.com/questions/43061878/facebook-oauth-stopped-working-suddenly)

Maybe it's time to update :)

**Comment by elektro-NIK** [comment]
Now you can use Chrome dev tools (in mobile view) to post photos.

**Comment by chen8160** [comment]
@elektro-NIK What do you mean? Does that somehow relate to OAuth?

**Comment by elektro-NIK** [comment]
@chen8160 No no. While the authorization is not fixed, instead of Ramme you can use mobile version of the Instagram (in Chrome dev tools) for publishing the photo from PC.
