### ISSUE TITLE
Can't toggle Dark Mode

### ISSUE THREAD

**Issue by yeskunall** [terkelg/ramme#25]
Hi @terkelg! First of all, I'd like to say that you've done a great job with the app! :grin:

Secondly, I can't seem to be able to toggle dark mode using said shortcut on my Windows machine. (`CTRL + D`)

Thanks for looking into the matter!

**Comment by terkelg** [comment]
Thanks for reporting this issue.

@neighborhood999 can you look at this?

**Comment by neighborhood999** [comment]
@terkelg On my Linux and Windows use `CTRL + D` can change to dark mode.

**Comment by neighborhood999** [comment]
@terkelg sorry My bad, is **can't**..

**Comment by terkelg** [comment]
Thanks for testing 👍  

That's strange though. I'll look into it

**Comment by terkelg** [comment]
Can you run and test the master after my 85ff6ff commit? Maybe this fixes the issue

**Comment by neighborhood999** [comment]
@terkelg it's not work. If I have more free time I will help this.

**Comment by terkelg** [comment]
Thanks!

**Comment by neighborhood999** [comment]
Fixed by #27

**Comment by yeskunall** [comment]
@neighborhood999 you just redid what @terkelg undid with 85ff6ff4a94e95d51dff0da5b1878a50f53a7041.
