### ISSUE TITLE
Unable to detect image files on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by parkcitymedia** [terkelg/ramme#258]
i actually have more information than <a href="https://github.com/terkelg/ramme/issues/255">issue #255</a>. i wouldn't consider this a duplicate

# issue
i hit the upload button (center [+] in the navbar) which opened up my file manager, navigated to my <b>~/Pictures/Screenshots</b> folder, which has ~10 .png files. Nothing showed up in the folder, and the "files of type:" menu was <i>blank</i>, and i was unable to click it and set it to "image files" or "all files".

# reproduce
- open the latest version of Ramme on ubuntu 16.04 LTS 64-bit (with xfce4 / thunar as your file manager), log in, and hit the <b>[+]</b> upload button, and your file manager should pop up.
- Navigate to a folder where you're 100% positive there are image files
- weep, because none of them show up
- attempt to change the type of files thunar searches for with the drop menu in the bottom right (which was really small and empty of any text for me) and weep harder because it does nothing when you click it.

# system
- ASUS Q550LF
- Ubuntu 16.04 LTS 64-bit
- Xfce4 desktop environment / Thunar FM

**Comment by GhitaB** [comment]
The same. It seems .png files can't be uploaded. But it works for .jpg files in my case.
