### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by giovannicaligaris** [terkelg/ramme#262]
Is there a possibility to have a PPA for Ubuntu?

**Comment by sudo-give-me-coffee** [comment]
With the appimage package, this would not be necessary

At least I think

 x64 version:

https://github.com/terkelg/ramme/releases/download/v3.2.3/Ramme-3.2.3-x86_64.AppImage

**Comment by giovannicaligaris** [comment]
Does the appimage tells you when there is a new release version?

The benefit of the PPA is that we get automatic updates.
