### ISSUE TITLE
Add DM Functionality

### ISSUE THREAD

**Issue by Suleman-Elahi** [terkelg/ramme#263]
There is an Instagram DM application for desktop is available (https://github.com/ifedapoolarewaju/igdm). I wonder if that can be integrated into this or add a new feature like that in this desktop app.

**Comment by gugadev** [comment]
That's a good idea and relatively easy to implement thorugh [instagram private api package](https://github.com/huttarichard/instagram-private-api). Maybe if I have free time this week do a PR.
