### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gamaanderson** [terkelg/ramme#265]
I'm trying to install compile the latest version on linux (Debian). When I run `yarn install`, all I got is

    yarn install v1.3.2
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@1.1.1: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    error electron-builder@19.37.2: The engine "node" is incompatible with this module. Expected version ">=6.0.0".
    error Found incompatible module
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by bil-elmoussaoui** [comment]
You need a newer version of node.

**Comment by gamaanderson** [comment]
thank you
