### ISSUE TITLE
 image doesn't fit preload window, scrolled splash

### ISSUE THREAD

**Issue by trappedinspacetime** [terkelg/ramme#266]
First of all, thank you for making such an app. It works well on my Ubuntu 16.04 platform. 
Splash screen or preload window image size unproportionate, so it scrolls the image to fit the window. 

https://ibb.co/h1HAn6

I wonder if it's specific to my platform.
Regards.
Kenn

**Comment by martindariocernadas** [comment]
Added my own issue to this : also under Ubuntu 16.04 (Kubuntu) , no splash screen is been loaded at all.
![seleccion_405](https://user-images.githubusercontent.com/26277326/41422783-0c677baa-6fd0-11e8-9bec-10ae0df46e0d.png)
