### ISSUE TITLE
"A JavaScript error occured in the main process"

### ISSUE THREAD

**Issue by Foxylizer** [terkelg/ramme#268]
### Description

Upon opening Ramme, an error window is opened.

### Steps to Reproduce

Download & Install Ramme.
Open Ramme. 
![image](https://user-images.githubusercontent.com/29559592/34420656-62f796d2-ebd0-11e7-9323-695186e5a655.png)

**Expected behavior:** I am able to use Ramme as normal.

**Actual behavior:** Ramme fails to work correctly.

**Reproduces how often:** Every time.

### Version

Ramme v3.2.3

### Additional Information

Output Log:
![image](https://user-images.githubusercontent.com/29559592/34420737-c07d19b2-ebd0-11e7-8afe-91d516012e81.png)

OS Specifications:
**Edition:** Windows 10 Home
**Version:** 1709
**Build:** 16299.125

**Comment by sabinich** [comment]
yep ;-(

<img width="418" alt="ramme_js-error" src="https://user-images.githubusercontent.com/1430016/52557121-7ac86100-2e29-11e9-95c5-32bb91229d06.PNG">
