### ISSUE TITLE
All the content of the screen is a bit to the right

### ISSUE THREAD

**Issue by telmotrooper** [terkelg/ramme#271]
I'm running Ramme 3.2.3-1 from the Arch User Repository and all the content of the screen is a bit to the right.

I took a picture to make it clearer: https://i.imgur.com/XI2j0Fv.png

**Comment by Depaulicious** [comment]
Same with the AppImage build.

**Comment by devnixio** [comment]
Confirmed in .deb build as well.

**Comment by octacian** [comment]
This has been fixed in the latest master, as the issue has been noted several times, and while there are probably a few more things that need to be fixed again before a new release, that's all that we're waiting for to get this fixed for the public.
