### ISSUE TITLE
adjust  white space 

### ISSUE THREAD

**Issue by swathigrate** [terkelg/ramme#274]
hello sir ... 

 thanks  for  grate app..... 
i'm facing little  bit  problems ......
1. not  able to send  stories ... showing a  message that  "rotate your device to add your story" ...
2. white space ... fix  css or layout 
3. not  giving notifications 
4. not refreshing posts or feeds   
![fetterevcvdf](https://user-images.githubusercontent.com/14991260/35325569-2bf17d24-011a-11e8-99ac-595d478908f1.jpg)

![fdftt](https://user-images.githubusercontent.com/14991260/35325168-ed793f88-0118-11e8-8832-59f7974799ab.jpg)
please  slove those   problams .. 
thanks q

**Comment by jovanzers** [comment]
![image](https://user-images.githubusercontent.com/12684238/36187879-d80ae8fa-117a-11e8-9cec-e316bce8ab4c.png)
me too, same here.. :( please fix

**Comment by matheusmcy1** [comment]
![captura de tela de 2018-03-16 22-17-41](https://user-images.githubusercontent.com/6350505/37550196-f6d3d74c-2967-11e8-8739-f58da2a82342.png)

The same problem.

**Comment by Bitlitas** [comment]
Can't upload daily story too, because of rotate bug :)

**Comment by franciscorichter** [comment]
same here. OS: Ubuntu Mate.
