### ISSUE TITLE
dist/renderer/styles/app.css not found in /opt/Ramme/resources/app.asar

### ISSUE THREAD

**Issue by hacker1024** [terkelg/ramme#275]
Built and installed on arch linux.
There is only an SCSS file in the asar.

```
Uncaught Exception:
Error: ENOENT, dist/renderer/styles/app.css not found in /opt/Ramme/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:513:9)
    at WebContents.page.on (/opt/Ramme/resources/app.asar/src/main/index.js:154:23)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by makmm** [comment]
Same problem, with both the .tar.gz and the .pacman. Help?

**Comment by anatolinicolae** [comment]
After some basic research I think the issue might be of SASS files not getting compiled due a lack of libsass on arch, can anyone confirm you can do that?

**Comment by makmm** [comment]
@anatolinicolae What do I do, just try to build?

**Comment by hacker1024** [comment]
@anatolinicolae The PKGBUILD in the AUR package just downloads the .deb and extracts it. It doesn't compile anything.

**Comment by hacker1024** [comment]
@anatolinicolae There's no error anymore, whether I build the app with libsass installed or not. However, in both cases, the sidebar doesn't show up at all, and the only button at the bottom is the upload button. There's no way to access any other pages.

**Comment by hacker1024** [comment]
I tried building v3.2.3 - there's still no error either way, but the buttons are at the bottom, and there's space where the sidebar should be.

**Comment by anatolinicolae** [comment]
## Sidebar Missing
Yeah, I removed the sidebar thing in the last release 'cause I didn't have enough time to fix it.

## #275
Regarding the SASS assets, I decompressed myself the pacman package and found the same as reported before. Cannot actually tell where's the problem though. The build script builds assets once, then should package the same compiled assets into destination-specific packages, which doesn't seem to happen... 🤔

**Comment by anatolinicolae** [comment]
Can you guys try building the app with a little change? Try with `dist/main` instead of `src/main` in [app/package.json](https://github.com/terkelg/ramme/blob/master/app/package.json#L3) and let me know if the final package works fine and loads correctly.

**Comment by aleshh** [comment]
Just installed 3.2.5 via regular dmg and getting this error on launch (old Mac running Sierra). Everything seems to work fine after I dismiss it tho, so win.

![screen shot 2018-07-10 at 3 18 22 am](https://user-images.githubusercontent.com/4977780/42501749-a172e72c-83f1-11e8-8f15-e17d1d54acd7.png)

**Comment by namyrb** [comment]
Also getting this same message in ubuntu 14.04:

![ramme_error_1](https://user-images.githubusercontent.com/41500254/43032498-0dcde3e4-8c6d-11e8-833e-5fcfc4e5cfe6.png)

And after I quit out:

![ramme_error_2](https://user-images.githubusercontent.com/41500254/43032503-18a57782-8c6d-11e8-8f32-107fa8383a74.png)

**Comment by sorenbug** [comment]
I'm getting the same issue on GalliumOS whether I install the deb using dpkg or build from source using yarn dist.

**Comment by elartix** [comment]
OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-29-generic

![image](https://user-images.githubusercontent.com/1899626/45543340-fbecdf00-b81c-11e8-99bb-6861716cd3d8.png)

**Comment by parzevil** [comment]
Error at every startup on Ubuntu 18.04 after installing from amd64.deb:
![errorramme](https://user-images.githubusercontent.com/31453761/45595006-e2769f00-b9a4-11e8-9d63-9fcb9b5acf44.png)

**Comment by gnanet** [comment]
> Error at every startup on Ubuntu 18.04 after installing from amd64.deb:
> ![errorramme](https://user-images.githubusercontent.com/31453761/45595006-e2769f00-b9a4-11e8-9d63-9fcb9b5acf44.png)

Same here 18.04 amd64.deb of 3.2.5

**Comment by gabomontero89** [comment]
Same here, ubuntu 18.04 (Ramme_3.2.5_amd64.deb)
![screenshot_2019-01-25_12-56-28](https://user-images.githubusercontent.com/25494196/51763500-c4caec00-20a0-11e9-82d8-bf6c9f94187e.png)

**Comment by ivogrig** [comment]
Same with ubuntu 16.04 and Ramme_3.2.5_amd64.deb

**Comment by abdeelmadjid** [comment]
same problem on windows 10 pro Ramme-Setup-3.2.5.exe  but the app run  normall after closing the dialog 
![image](https://user-images.githubusercontent.com/42095844/58906514-f49b9780-8703-11e9-900e-dd32664b6217.png)
![image](https://user-images.githubusercontent.com/42095844/58906576-201e8200-8704-11e9-9638-b815193c679f.png)
