### ISSUE TITLE
i cant log out of ramme

### ISSUE THREAD

**Issue by gozieugo99** [terkelg/ramme#276]
ive been trying for days now to log out of ramme i just cant please fix this 
            -

            Ramme 3.2.3
            Electron 1.7.2
            linux x64 4.13.0-26-generic

**Comment by rielinux** [comment]
Hi there...I also had this problems, login & logout buttons are missing event if i make Ramme's windows larger.

Ramme_3.2.3_i386(1).deb
OS Kali Linux 4.13.4-2kali1 

Hope you can fix this issues #thankyou
