### ISSUE TITLE
I don't know how to install it on Ubuntu 16.04

### ISSUE THREAD

**Issue by artigxs** [terkelg/ramme#28]
I'm a newbie, so I did what instructions says that I have to do. I unzipped the file somewhere but I can't execute Ramme. I'm looking for a solution thru blogs and stuff but I can't put my finger in the solution.

Please, help. I need a How to Install Ramme on Ubuntu for Dummies :smile: I really wanna try Ramme :cry:

**Comment by terkelg** [comment]
Hi @artigxs 
I don't have Ubuntu myself, but did you download the compiled Ramme from the "release" tab, or did you download the source itself?

**Comment by seanr707** [comment]
@artigxs 

Try unpacking Ramme into a folder name "Ramme" in your home folder. So if you are 'bob', then the files should be in `/home/bob/Ramme`.

Next open terminal window. Type in `cd Ramme`.

Next, type `./Ramme`

If you get an error saying the file is not executable, then type the following:

`chmod +x Ramme`

Try `./Ramme` again, and it should open the program!

**Comment by artigxs** [comment]
I did it from the release tab, @terkelg. 

Hey, @seanr707. I tried this but i'm still getting an error `bash: ./Ramme: can not execute the binary file: Executable format incorrect` :confused:

**Comment by terkelg** [comment]
Thanks for helping out with this @seanr707!

**Comment by seanr707** [comment]
@artigxs That sounds like that you have the incorrect binary (i.e. It is the Windows or OS X version). Check and make sure the zip file you have is `Ramme-linux-2.1.0.zip`.

@terkelg You're welcome!

**Comment by artigxs** [comment]
@seanr707 I downloaded Linux version, but now I try downloading and installing the 2.1.0 release and I still getting same error.

I don't know what to do :sob:

**Comment by seanr707** [comment]
@artigxs Hmm, well then my next guess is that you are running a 32 bit version of Ubuntu? I'm looking at the source code and it looks like the Linux package is build for 64 bit OS's.

**Comment by artigxs** [comment]
Oh, yeah, i'm running a 32 bit version! Well, I guess I can't do anything more :disappointed: But thank you, for taking care of this problem, I'm really grateful :smile:

**Comment by seanr707** [comment]
@artigxs No worries, wait a couple of minutes and I should have the 32-bit version built.

**Comment by seanr707** [comment]
@artigxs Here is a link to a [32-bit Linux build](https://www.dropbox.com/s/aj2ep6bexxpj6it/Ramme-linux32-2.1.0.zip?dl=0)

Build option was added in Pull Request #37 

Issue should now be resolved

**Comment by terkelg** [comment]
Thanks for the support on this one @seanr707. It's a huge help

**Comment by artigxs** [comment]
Thanks for the big help, @seanr707. I'm already using it and it's really great. It's more confortable than the web, @terkelg.  :smile: :+1:
