### ISSUE TITLE
The application EULA contradicts the license

### ISSUE THREAD

**Issue by Calinou** [terkelg/ramme#280]
The application's EULA (noted below) contradicts the [MIT license](https://github.com/terkelg/ramme/blob/master/LICENSE) the source code is licensed under, which allows [using the software for any purpose](https://www.gnu.org/philosophy/programs-must-not-limit-freedom.en.html) (even though it does not make illegal actions legal; no software license is able to do that).

> ## End User License Agreement (EULA)
> - You will not use this repository for sending mass spam or any other malicious activity.
> - We / You will not support anyone who is violating this EULA conditions.
> - Repository is just for learning / personal purposes thus should not be part of any service available on the Internet that is trying to do any malicious activity (mass bulk request, spam etc).

Would you please consider removing this section? This way, this application would comply with the [Open Source Definition](https://opensource.org/osd) and the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html).

**Comment by JohnMH** [comment]
To clarify, this project is currently under the Expat license, with an additional non-binding EULA. As it is an implicit contract, and there is no guarantee that end users would ever see this EULA anyway, it's not very useful as it is.

**Comment by terkelg** [comment]
Removed
