### ISSUE TITLE
Can't comment, full screen and switch to dark background

### ISSUE THREAD

**Issue by pu3antasyah** [terkelg/ramme#284]
Since last night I can't comment to any IG post with Ramme and make it full screen. Also since I install it, I can't change the background to dark.

Ubuntu 16.04 LTS Unity

**Comment by pu3antasyah** [comment]
Okay, today it's working again:

1. Can comment

2. Full screen working better than before, it's show UI/EX like official web Instagram. But with Ramme had option to upload!

3. Swtich to dark still never working. It's just dark for few second then flashing go back to light.

**Comment by anatolinicolae** [comment]
Glad it fixed itself. The thing is this is a wrapper of the web version, so whatever they change we have to adjust here but terkel worked out a "static class-based" theming, so that's why you can't switch to dark...
