### ISSUE TITLE
There is no Logout link

### ISSUE THREAD

**Issue by ardubit** [terkelg/ramme#285]
-

            Ramme 3.2.3
            Electron 1.7.2
            darwin x64 17.4.0

**Comment by aleshh** [comment]
Yeah, how do I log out? Delete configuration files??

**Comment by bigpoppaken** [comment]
Yeah I definitely want a logout button in the window or something in the tray icon menu (Linux) I have two accounts so I wanna log out and log into the other one. It seems once I'm logged in I'm just logged in.

**Comment by anatolinicolae** [comment]
Have you tried updating to the latest release and going to your profile, over the cog button to Settings and then Logging out at the bottom?

**Comment by bigpoppaken** [comment]
I originally installed it through electron. So I uninstalled it and downloaded and installed the .deb from git so its fine now.
