### ISSUE TITLE
could ramme support proxy for that chinese cannot visit Instagram directly,

### ISSUE THREAD

**Issue by ermazi** [terkelg/ramme#287]

**Comment by v0idst4r** [comment]
Ramme already supports this (or other supports applications that'll load proxies)

**Comment by octacian** [comment]
This isn't something that needs, in particular, to be supported by Ramme itself, but it is rather something that you should configure in your OS. In fact, every OS that I know of right now supports using a VPN or some other proxy service to redirect traffic for all or specific applications on the computer through the aforementioned proxy.

With this in mind, the feature requested is not something that would typically be implemented within any arbitrary application, but rather a feature that already exists in the OS itself. Closing the issue.
