### ISSUE TITLE
Ramme not remembering login info

### ISSUE THREAD

**Issue by 32gits** [terkelg/ramme#296]
After telling the app to save my login info, sometimes when I quit the app and reopen I have to login again.

**Comment by anatolinicolae** [comment]
Does that happen on the web version too? I think this does happen when you frequently switch networks which leads to you session to be terminated.

**Comment by 32gits** [comment]
@anatolinicolae Hmm. Could be related to the fact that I'm on a VPN then?

**Comment by anatolinicolae** [comment]
If you do constantly use the VPN and you don't visit instagram while not on VPN, no. Otherwise yes.

Give it a try on the browser. Log on the site, switch networks, wait some time, switch again, and so on... This behaviour should ask you to login in again... 🤷‍♂️

**Comment by comtech2011** [comment]
and also it does not update the feeds

**Comment by anatolinicolae** [comment]
Then it's definitely an Instagram issue since we do not set cookie or token expires...

**Comment by Caver1** [comment]
Is it an Instagram Issue? As it seems that only a couple of us has asked about this problem could it be something else?
Possibly an OS update? I'm using Ubuntu 16.04. Just wondering.

**Comment by anatolinicolae** [comment]
I'm on Mac with Chrome and this has been happening to me lately on the web version 🤷‍♂️
