### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by SethCalkins** [terkelg/ramme#301]
Receiving the following error whenever application is launched.

`Uncaught Exception:
Error: ENOENT, dist/renderer/styles/app.css not found in /Applications/Ramme.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:518:9)
    at WebContents.page.on (/Applications/Ramme.app/Contents/Resources/app.asar/src/main/index.js:156:23)
    at emitOne (events.js:116:13)
    at WebContents.emit (events.js:211:7)`

**Comment by traBolic** [comment]
Same on Ubuntu 18
![screenshot from 2018-07-31 23-30-29](https://user-images.githubusercontent.com/5789670/43485408-cdc49760-9519-11e8-8499-0422612f476a.png)

**Comment by parzevil** [comment]
Got error too on Ubuntu 18.04:
![errorramme](https://user-images.githubusercontent.com/31453761/45594966-2026f800-b9a4-11e8-8840-22cc4e7c31c3.png)

**Comment by jonorozcoc** [comment]
![image](https://user-images.githubusercontent.com/8442497/45697189-d4eb2180-bb2a-11e8-80a3-7630818c968a.png)

The same in Windows 7

**Comment by arthurdapaz** [comment]
Same...

**Comment by philliptee** [comment]
What do

**Comment by xolonavt** [comment]
Ramme version 3.2.5 Same issue: 
Windows 10 1709 
java ver 8 update 181 (build 1.8.0_181-b13)
![2018-10-16_15-43-08](https://user-images.githubusercontent.com/44199811/47017153-33231880-d15a-11e8-9379-e3dfc7085f75.png)

**Comment by Krymancer** [comment]
I get this error in version 3.1.5 in Debian 9
![captura de tela de 2018-11-02 00-06-47](https://user-images.githubusercontent.com/17505605/47891733-40ffbb80-de33-11e8-9fdd-319d2abc0164.png)

**Comment by RaihanStark** [comment]
Same here

**Comment by ghusto** [comment]
Same here on debian 9

**Comment by ghusto** [comment]
Same here on debian 9
![2018-11-03 06-07-54](https://user-images.githubusercontent.com/21106479/47947923-024f2b80-df2f-11e8-8398-d0e7b87ccf7e.png)

**Comment by omortie** [comment]
![screenshot from 2018-11-20 22-17-04](https://user-images.githubusercontent.com/38497452/48795426-1ad28a80-ed12-11e8-9a1e-d5206667f8f6.png)
same here!
is there any solution?

**Comment by traBolic** [comment]
> I get this error in version 3.1.5 in Debian 9
> ![captura de tela de 2018-11-02 00-06-47](https://user-images.githubusercontent.com/17505605/47891733-40ffbb80-de33-11e8-9fdd-319d2abc0164.png)

Mentioned in #311

**Comment by traBolic** [comment]
Guys, you don't need to add another comment for the same problem. Just use the reaction button to add thumb emoji 
![image](https://user-images.githubusercontent.com/5789670/49345914-35a2e880-f69c-11e8-85c8-1555ccacd209.png)
