### ISSUE TITLE
Uncaught Exception in v3.2.5

### ISSUE THREAD

**Issue by MarceloRuiz** [terkelg/ramme#302]
I get an uncaught exception when running Ramme on Ubuntu 18.04 amd64:

```
Type Error: Cannot read property 'name' of undefined at getConf (/opt/Ramme/resources/app.asar/node_modules/first-run/index.js:13:73)
at firstRun /opt/Ramme/resources/app.asar/node_modules/first-run/index.js:25:13)
at Object.exports.init (/opt/Ramme/resources/app.asar/src/main/analytics.js:14:7)
at App.app.on (/opt/Ramme/resources/app.asar/src/main/index.js:89:13)
at emitTwo (events.js:131:20)
at App.emit (events.js:214:7)
```

**Comment by denis4net** [comment]
The same issue
![image](https://user-images.githubusercontent.com/2119348/44625612-2c281880-a916-11e8-9fd5-b219b4493b2f.png)

**Comment by RogerBergling** [comment]
Same here, Ubuntu 18.04, java version "1.8.0_181"
![image](https://user-images.githubusercontent.com/32700412/46523942-932adc80-c887-11e8-8d80-fb1b07cea459.png)

**Comment by jouhoff** [comment]
Same here on Win10
node v10.13.0

**Comment by marvinborner** [comment]
Same here on Arch Linux with node v11.3.0

**Comment by AndrecioBezerra** [comment]
Here also! Linux Mint 18.3 (Sylvia) node V10.15.3
