### ISSUE TITLE
Can't post stories (since you can't rotate screen)

### ISSUE THREAD

**Issue by QDesjardin** [terkelg/ramme#303]
Title is self-explanatory - clicking on the New Story icon tells you to rotate your screen, but there's no way of doing this yet in Ramme.

**Comment by bentref** [comment]
I am having this issue too. I'm not seeing much activity in this project, so don't get your hopes up for a fix anytime soon :-/

**Comment by WindowsAndLinux** [comment]
Same here

**Comment by pablorome** [comment]
so there is nobody to fix this?
im still learning javascript can't do it myself yet
is actually usefull to manage my clients ig

**Comment by pablorome** [comment]
SDFSDF i think i found a hotfix to this issue!
since the program uses chromium to work if you just press ALT you can switch to dev mode then you can click on the device button.
this should work
love
