### ISSUE TITLE
Javascript Error on Mac

### ISSUE THREAD

**Issue by ghost** [terkelg/ramme#306]
When opening Ramme 3.2.5 on mac running Mojave OS 10.14 public beta I get a javascript error pop up...

<img width="668" alt="screen shot 2018-08-29 at 9 58 03 am" src="https://user-images.githubusercontent.com/42789302/44757501-d3a18700-ab72-11e8-9e7e-154426399d2c.png">
Image attached!
            -

            Ramme 3.2.5
            Electron 2.0.3
            darwin x64 18.0.0

**Comment by pmunozroa** [comment]
![image](https://user-images.githubusercontent.com/40769812/44939940-9221ff00-ad5f-11e8-9f62-85ccda4272a3.png)
same Error on Linux

**Comment by GXGOW** [comment]
![screenshot from 2018-09-05 12-34-07](https://user-images.githubusercontent.com/14166923/45087995-0108aa80-b108-11e8-8d60-1f94b2aface0.png)  
Same thing here, running Arch Linux.

**Comment by elcombechris** [comment]
![capture](https://user-images.githubusercontent.com/40341717/45269250-c03ac980-b458-11e8-8f24-4760bc711eb6.PNG)

Same thing, Windows 10 x64.

Note while I see this error on almost every screen I open I was able to login and view pictures.

**Comment by parzevil** [comment]
Ubuntu 18.04 with amd64.deb:
![errorramme](https://user-images.githubusercontent.com/31453761/45594988-87dd4300-b9a4-11e8-9d46-86a2a803bc7c.png)

**Comment by Lailah** [comment]
I have exactly the same issue in Fedora 28 KDE Spin  (64-bits).

**Comment by solarkraft** [comment]
Same problem on Elementary OS Loki. Also looks nothing like advertised. 
![image](https://user-images.githubusercontent.com/1337470/48292992-29e94b00-e47d-11e8-862b-8673ff07e96e.png)
I guess a glorified web view would be okay if it wasn't so heavy and wouldn't throw tons of errors.

**Comment by uhlhosting** [comment]
Uncaught Exception:
Error: ENOENT, dist/renderer/styles/app.css not found in /Applications/Ramme.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:518:9)
    at WebContents.page.on (/Applications/Ramme.app/Contents/Resources/app.asar/src/main/index.js:156:23)
    at emitOne (events.js:116:13)
    at WebContents.emit (events.js:211:7)

**Comment by luk0y** [comment]
> I have same problem. Windows 10 x64
> ![image](https://user-images.githubusercontent.com/20737945/51060382-d7efad80-1604-11e9-8351-cc2a9653f956.png)

I am thinking that you have node.js installed on your pc . Uninstall nodejs from your pc and try opening ramme. I hope it solves your issue .
