### ISSUE TITLE
switch accounts

### ISSUE THREAD

**Issue by Vahid-Peivandi** [terkelg/ramme#308]
hi 
on Ramme 3.2.5 I have multiple accounts but do not save login information but earlier i see switch account  but now do not see and save information
please fix it

**Comment by anatolinicolae** [comment]
Pretty sure @facebook can do that on Instagram Web.

**Comment by Vahid-Peivandi** [comment]
> Pretty sure @facebook can do that on Instagram Web.

can you explain in the simplest way and step by step, please??

**Comment by Jkings777** [comment]
i wondering, do you don't mind use  Western-Union ? i mean i have to cash
in a person, then send you via recipient, you to get in person near you by
Western union  to get a cash? let me know
