### ISSUE TITLE
Uncaught exception on start and close.

### ISSUE THREAD

**Issue by adrianbrosz** [terkelg/ramme#311]
There are two uncaught exceptions, one when starting Ramme:

![zrzut ekranu z 2018-10-30 07-48-13](https://user-images.githubusercontent.com/29169682/47700897-5b118200-dc18-11e8-90d8-5dbad3b60ce8.png)

and one on exit:
![zrzut ekranu z 2018-10-30 07-47-55](https://user-images.githubusercontent.com/29169682/47700908-6b296180-dc18-11e8-85c1-68394351078d.png)

**Comment by Gaspacchio** [comment]
I confirm this issue, I'm having the same one using Ubuntu with and XFCE desktop environment.

**Comment by traBolic** [comment]
Duplicate of #301

**Comment by ir1keren** [comment]
I confirm this issue, I'm having the same one using Linux Mint Cinnamon 18.3
![screenshot from 2018-12-01 12-57-06](https://user-images.githubusercontent.com/1435149/49324837-a5b05200-f568-11e8-9b0c-3d9b1b4fb66d.png)

**Comment by XXN** [comment]
I confirm this issue on Windows too (Seven Ultimate).
http://prntscr.com/lppilw
http://prntscr.com/lpplbc

**Comment by traBolic** [comment]
Guys, you don't need to add another comment for the same problem. Just use reaction button to add thumb emoji 
![image](https://user-images.githubusercontent.com/5789670/49345914-35a2e880-f69c-11e8-85c8-1555ccacd209.png)

**Comment by adrianbrosz** [comment]
The problem is that this project is no longer maintained by anyone ;-)

**Comment by coolrecep** [comment]
Same on Windows: 
![image](https://user-images.githubusercontent.com/13221472/50707600-66e34f80-1072-11e9-8bc2-b2bbb54e153a.png)

**Comment by jonorozcoc** [comment]
Duplicate of #301
