### ISSUE TITLE
Electron 2.0.3 and glibc 2.28 segfault at startup

### ISSUE THREAD

**Issue by conraid** [terkelg/ramme#312]
Electron 2.0.3 segfault at startup on linux with glibc 2.28 (I'm using Slackware current).
https://github.com/electron/electron/issues/13972
Please consider using Electron >= 2.0.8 for next realese.

Thanks 
Conraid

**Comment by Lailah** [comment]
Yes, this happens to me too. I have segmentation fault in startup.
I'm using  Fedora 29 KDE Spin.

**Comment by rizzini** [comment]
Same thing here. Using Ubuntu 18.19 - amd64. Tried the .deb and .tar.gz. Same error.
