### ISSUE TITLE
"Please wait a few minutes before you try again"

### ISSUE THREAD

**Issue by buha** [terkelg/ramme#316]
My instagram account got messed up after logging in using ramme.

By logging in in a browser I get this. This is the whole HTML response ! 
{"message": "Please wait a few minutes before you try again.", "status": "fail"}

The Android app is also messed up and doesn't show anything related to my account.

I suspect ramme did something that triggered some weird (maybe buggy) security feature of instagram.

Other instagram users have seen this error but don't mention ramme. https://www.reddit.com/r/Instagram/comments/7obmci/instagram_problem/

**Comment by anatolinicolae** [comment]
Have you tried #196 or #296?

**Comment by buha** [comment]
#196 can't be the case, I don't have 2 step verif on. #296 neither, my login was saved properly.

My issue got resolved as per the old reddit thread... after some time. Maybe half a day or so.
As it's impossible for me or you to reproduce it, I'm closing this issue.
