### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by agvozdezkiy** [terkelg/ramme#320]
Ubuntu 18.10: sudo dpkg -i Ramme_3.2.5_amd64.deb
Displays an error "Segmentation fault (core dumped)" when run the app.

Ramme_3.2.3_amd64.deb - don't toggle in dark mode

**Comment by anatolinicolae** [comment]
#312 and [#204#389351172](https://github.com/terkelg/ramme/issues/294#issuecomment-389351172)
