### ISSUE TITLE
{"message": "Please wait a few minutes before you try again.", "status": "fail"}

### ISSUE THREAD

**Issue by Majora190** [terkelg/ramme#322]
I'm not sure why this problem is occurring, but when I try to open Ramme, I just get this. I would love some help.

**Comment by Farioko** [comment]
Please fix this.

**Comment by MatheusRich** [comment]
According to [this thread](https://www.reddit.com/r/Instagram/comments/ahjoj9/message_please_wait_a_few_minutes_before_you_try/) this happens when there's too many requests. There's a rate limit of 200 requests/hour (https://developers.facebook.com/docs/instagram-api/overview/).
