### ISSUE TITLE
Crash upon startup on Ubuntu 18.10

### ISSUE THREAD

**Issue by ZZZXXX0110** [terkelg/ramme#323]
Crash upon startup on Ubuntu 18.10.

Can be partially fixed and successfully start up by manually change the /opt/Ramme/libnode.so with a newer version as mentioned here: https://github.com/electron/electron/issues/13972#issuecomment-433001316. However, this cause numerous Javascript error messages to pop up after launch.

**Comment by derdjme** [comment]
Same problem here, too.

**Comment by carestad** [comment]
Probably the same as #321
