### ISSUE TITLE
Not working on Ubuntu 19.04

### ISSUE THREAD

**Issue by fernandex00** [terkelg/ramme#330]
Just updated to ubuntu 19.04, and ramme won't open

**Comment by MrSiRaX** [comment]
same here

**Comment by viggou** [comment]
Same problem on Debian 10 buster

**Comment by hmdshariati** [comment]
Segmentation fault (core dumped)

**Comment by msnjuegos** [comment]
same here on Debian 10 buster

**Comment by The1st7th** [comment]
same on pop_OS

**Comment by Shekhar12121** [comment]
same problem @asood123

**Comment by fabianskibr** [comment]
previous relase 3.2.3 its partially working with bugs on kubuntu

**Comment by FcoMarcosMAbreu** [comment]
I've just installed Ramme... ¬¬

**Comment by ItsCDubb** [comment]
I've got the same issue, it's not running at all, are there any work arounds for this?

**Comment by ItsCDubb** [comment]
I've downloaded the 3.2.3 version in appimage format until we can get the new one working

**Comment by arivle** [comment]
@fabianskibr same here. Installed ramme 3.2.5 in kubuntu 19.04, and keep crashing

**Comment by mexin** [comment]
Same here with Pop_OS 19.04, when trying to run from terminal I get a `Segmentation fault (core dumped)`

**Comment by hcw70** [comment]
Same here with 3.2.5 in Ubuntu 19.04.  Segmentation fault.

**Comment by risalfajar** [comment]
Same here. Segmentation fault on Pop_OS! 19.04
