### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by mariarti** [terkelg/ramme#333]
Ramme_3.2.5_amd64.deb
Ubuntu 18.04 x64 with latests updates
![Screenshot from 2019-05-13 19-43-44](https://user-images.githubusercontent.com/1933140/57643892-17ca9f80-75bb-11e9-8895-e44c19ff3d4d.png)

**Comment by 1F1R5T** [comment]
same with me

**Comment by diggis00** [comment]
Same here in windows 10 64-B
![Annotation 2019-06-21 232935](https://user-images.githubusercontent.com/30402460/59942525-8e41a380-947d-11e9-8eda-e447714a7bd5.jpg)
it

**Comment by MatheusRich** [comment]
Same here with Linux Mint 18.3

**Comment by 98ht24** [comment]
same here in ubuntu 18.04

**Comment by PauloBoaventura** [comment]
Centos 7 too

**Comment by katyasehgal** [comment]
Same
