### ISSUE TITLE
Javascript Error in Arch Linux

### ISSUE THREAD

**Issue by shashinvision** [terkelg/ramme#334]
![image](https://user-images.githubusercontent.com/33522282/57787076-bca3c480-7702-11e9-91eb-29224aede339.png)

**Comment by butterchoco** [comment]
I solve this by updating Ramme to the new one. Hope it can help u ! :)

**Comment by mrshroomy** [comment]
This problem isn't fixed in ubuntu repositories

**Comment by efirshik** [comment]
+1, Ramme_3.2.5_amd64. Ubuntu 18.04.2 LTS.
![Screenshot from 2019-07-12 20-16-17](https://user-images.githubusercontent.com/43796942/61142922-f9612180-a4e1-11e9-8aa4-4e3afacc6261.png)
