### ISSUE TITLE
Java Script error -Windows

### ISSUE THREAD

**Issue by msebastian100** [terkelg/ramme#336]
Hello,
I always get this Java error on Windows [See picture]
![2019-07-17_18h11_57](https://user-images.githubusercontent.com/4114151/61387894-a7444580-a8bf-11e9-8be7-c7b3f06383c6.png)

Can you fix that somehow?

greetings

**Comment by issakomi** [comment]
The same on Linux, that error message appears frequently, but app works

![Screenshot at 2019-07-20 21-54-03](https://user-images.githubusercontent.com/1494580/61583515-3314d680-ab39-11e9-9294-382b82362e14.png)

**Comment by svastian99** [comment]
I have the same problem .. besides problems with the icon in Cinnamon 4.2.3
https://i.postimg.cc/g28Jdvvk/57.png

greetings

**Comment by roberthchan** [comment]
Same issue in MacOS 10.14.6

<img width="532" alt="Screen Shot 2019-10-23 at 4 04 47 PM" src="https://user-images.githubusercontent.com/43115025/67439000-ac99e600-f5ba-11e9-8955-b213366fa98e.png">

Thanks!
