### ISSUE TITLE
why can't any activity?

### ISSUE THREAD

**Issue by Vahid-Peivandi** [terkelg/ramme#341]
-

            Ramme 3.2.5
            Electron 2.0.3
![Screenshot at 2019-08-28 20:05:09](https://user-images.githubusercontent.com/25903079/63870604-8c411700-c9cf-11e9-9334-0f14c46f383d.png)

            linux x64 4.4.0-124-generic

**Comment by Youboontoo** [comment]
This is an issue with your account on Instagram, not with the program.
https://help.instagram.com/
