### ISSUE TITLE
App window gets stuck

### ISSUE THREAD

**Issue by celebrion** [terkelg/ramme#36]
After some scrolling in the feed, the Ramme window gets stuck on the screen, i.e. it's impossible to move around on screen. If the view is changed (e.g. to profile) and then back to feed again, the window becomes movable again.

            Ramme 2.0.0
            Electron 1.3.4
            darwin x64 15.6.0

**Comment by terkelg** [comment]
Thanks for reporting this! I had this issue myself some time ago, but thought I had fixed it.

**Comment by vintagesucks** [comment]
@celebrion Same issue with Ramme 2.1.0?

**Comment by celebrion** [comment]
Can confirm that the issue exists in 2.1.0 as well.

**Comment by terkelg** [comment]
Alright, I'll look at a solution to this. I'm not quite sure why this is happening

**Comment by terkelg** [comment]
It's happening the second the first new batch of photos are loaded. Still trying to find a solution, without making everything ```-webkit-app-region: drag; ```

**Comment by terkelg** [comment]
Awesome!
