### ISSUE TITLE
Hardcoded links in website

### ISSUE THREAD

**Issue by terkelg** [terkelg/ramme#38]
Link to releases with `https://github.com/terkelg/ramme/releases/latest` instead.

**Comment by seanr707** [comment]
Working on a microAPI that would allow you specify a url and a generic filename and it route to the latest release. Have it [possibly] functioning on my PC, Next step is to work on deployment/testing.

**Comment by seanr707** [comment]
microAPI deployed at https://arcane-forest-77480.herokuapp.com/

When given proper queries it redirects the user to the newest download for the file given in the link. 

Working when tested on my [fork](https://github.com/seanr707/ramme/tree/38-dynamic-download-links)

Pull #39

**Comment by terkelg** [comment]
Thanks @seanr707 and @anatolinicolae. I prefer to keep the code in the open, so I think we go with #43. You guys rock!

**Comment by seanr707** [comment]
@terkelg No problem! I only chose the microservice because I couldn't embed Javascript in the README
