### ISSUE TITLE
"Open in app" should be hidden by default

### ISSUE THREAD

**Issue by gingerbeardman** [terkelg/ramme#4]
Obviously "Open in app" makes no sense on Desktop

![screen shot 2016-08-24 at 13 59 44](https://cloud.githubusercontent.com/assets/49612/17931366/0c8415e6-6a03-11e6-83c4-919a9c2ad0d5.png)

**Comment by terkelg** [comment]
Thanks for reporting it. I'll look at look at it

**Comment by gingerbeardman** [comment]
I'll have a quick look myself now that nam is working.

**Comment by terkelg** [comment]
It could be awesome. I appreciate your help. Thanks

**Comment by gingerbeardman** [comment]
First I need to figure out how to access the web inspector...

**Comment by terkelg** [comment]
`cmd+alt+i`

Then you can report the selector to me, or create a pull-request.

**Comment by gingerbeardman** [comment]
```html
<div class="_nl1vc _28zbs">
<div class="_h7ogh"></div>
<div class="_hcq2b"><span class="_hblvq"><a class="_9sso8" href="javascript:;">Open in app</a><a class="_jj6py" href="javascript:;">X</a></span>
</div>
</div>
```

`_h7ogh` is a strange rotating square.

will send pull request now

**Comment by gingerbeardman** [comment]
https://github.com/terkelg/ramme/pull/6
