### ISSUE TITLE
White border on top and bottom of images when viewing in profile images in dark mode

### ISSUE THREAD

**Issue by mckennajones** [terkelg/ramme#47]
There is currently a white border on the top and bottom of images that are viewed in profile view when dark mode is enabled. The same issue is not present when viewing the normal home page feed. It is a little distracting to me. Either way it should be consistent between the homepage and the profile view. I noticed that the screenshots in the README do not have this white border so it is probably best to remove it. Here is an example: 
![screenshot from 2016-09-12 11-16-59](https://cloud.githubusercontent.com/assets/7456446/18447301/e33e451c-78da-11e6-8c76-454e89ebc9ba.png)

**Comment by terkelg** [comment]
Fixed with #48 and #47. Thanks for reporting it!
