### ISSUE TITLE
multi account

### ISSUE THREAD

**Issue by man2** [terkelg/ramme#49]
I think it's a really nice feature to have, is it possible?

**Comment by anatolinicolae** [comment]
Nice feature, but actually not allowed by the web neither by the mobile version of Instagram. A trick may allow this to work by the way. @terkelg put this on hold for v3, I may get it working in some time.

**Comment by terkelg** [comment]
Maybe this is a cool thing to add in the fetature. I've decided that I'm open to use of Private API's in the future. Thanks for helping out with the repo @anatolinicolae.

**Comment by anatolinicolae** [comment]
Won't be a Private API, you'll just see what I'm talking about when I get some time to dive into it.

**Comment by terkelg** [comment]
I know, you can create a new window with a new session - just as private browsing does. But in generel, I'm open to the use of private APIs in the future.

**Comment by alkinkasap** [comment]
👍
