### ISSUE TITLE
photo upload

### ISSUE THREAD

**Issue by maxogden** [terkelg/ramme#51]
I'd be interested in working on this, has anyone looked into if theres even an API for it?

**Comment by anatolinicolae** [comment]
Even the API you can use for mobile apps doesn't allow this. There are some tricks that you can do though to fake the device and have an image post working. @terkelg I don't think we want to go against Instagram's TOS or legal stuff...

**Comment by terkelg** [comment]
I talked with @CaliAlec a few weeks ago, author of https://github.com/CaliAlec/ChromeIGStory, and he don't have any problems. This could be fun to build, and a nice addition.

Go ahead @maxogden, let's create a new branch and try this out.

**Comment by matijagrcic** [comment]
@terkelg You can look at [upload.js](https://github.com/huttarichard/instagram-private-api/blob/8efa29e94edf8f4fe08bbaf3de35aee5528eb6be/client/v1/upload.js#L26) and [media.js](https://github.com/huttarichard/instagram-private-api/blob/cc0f43f65e5373edeeb793afc1148e93baf8e836/client/v1/media.js#L105) from the https://github.com/huttarichard/instagram-private-api

**Comment by CaliAlec** [comment]
@maxogden @anatolinicolae @terkelg I'm about to release a CMS and Analytics dashboard for Instagram Stories which allows you to upload to your Story from the web. (http://devpost.com/software/mochi-instagram-stories-cms-and-analytics)

If you guys are worried about legal issues, you can wait until I release it and use me as a scapegoat, since Instagram will most likely send a Cease & Desist letter, however they never did for my Chrome extension.

**Comment by brandonmcconnell** [comment]
Interesting stuff. This might be worth looking into:
[https://itunes.apple.com/us/app/uploader-for-instagram-post/id969998518]

**Comment by englishextra** [comment]
Frankly, you will not gonna get this, it's business, and without upload option this app is completely useless and is a wrapper for instagramm site.

So stop fooling around people. Frankly, stop doing it.

**Comment by terkelg** [comment]
I've been busy lately and haven't been able to work on Ramme, but I'm sorry you find the app useless.

**Comment by brandonmcconnell** [comment]
I personally love the app. Keep it up!

**Comment by emporeso2** [comment]
@englishextra hey man don't be so rude !
Man you are yelling !
Let coders code man .
@terkelg ,i'am a linux user and i'am happy to have found your app owrking on my linux.
Take your take,it's not business, this is the quality that count.

**Comment by englishextra** [comment]
@emporeso2 Yeah-yeah

**Comment by lucianomunoz** [comment]
the one reason i'm looking for a desktop version of instagram is to upload videos an pics from y computer, will that ever be possible?, your app is really nice still.

**Comment by anatolinicolae** [comment]
Photo and video upload is definitely something we want to implement but currently there are no milestones for this since we have few bugs to fix atm.

**Comment by earthbound19** [comment]
+1 this would be awesome, and thanks regardless for the very handy application.

**Comment by aranajhonny** [comment]
@terkelg I've tried with https://github.com/huttarichard/instagram-private-api and uploading images works quite well. But I do not know if you would agree to use a third party API to enable this and other functions.

**Comment by anatolinicolae** [comment]
That's actually great @aranajhonny! Go ahead and submit a pull request! 🎉

**Comment by terkelg** [comment]
Sounds awesome @aranajhonny. Create a pull request and let's have a look 👍

**Comment by earthbound19** [comment]
The tools at the repository linked as "similar" at the end of the readme at yon repository--I've tried this via CLI on windows (using a provided example) and it uploads ok:

https://github.com/mgp25/Instagram-API

**Comment by aranajhonny** [comment]
With javascript this is possible https://github.com/aranajhonny/ig-upload. The problem is that you have to rewrite much of this application. Especially for the authentication part, currently it is a wrapper of instagram website. The adoption of an api would facilitate this and other [things.](https://github.com/terkelg/ramme/issues/106)

**Comment by terkelg** [comment]
Looks really good @aranajhonny! Maybe we should switch from wrapping the website to just use the unofficial api and build our own front-end?

**Comment by terkelg** [comment]
Photo upload now possible. I'm going to update the app to accommodate the new feature.

**Comment by Fincer** [comment]
This sounds great @terkelg! Keep up the good work!
