### ISSUE TITLE
Split code into modules and clean up.

### ISSUE THREAD

**Issue by terkelg** [terkelg/ramme#52]

**Comment by anatolinicolae** [comment]
Which ESLint config would you like? Should we stick with the most known/big such as [Google](https://github.com/google/eslint-config-google), [Airbnb](https://github.com/airbnb/javascript)?

**Comment by terkelg** [comment]
ESLint isn't needed anymore - We're now using Standard in the main repo (https://github.com/feross/standard)

**Comment by anatolinicolae** [comment]
Have to lint some files anyway...

**Comment by terkelg** [comment]
I'm not sure I know what you mean? Standard do lint, and actually uses ESLint behind the scenes

**Comment by anatolinicolae** [comment]
Yeah, but we have to run it in the repo files since there are Standard rules are not fully applied yet.

**Comment by terkelg** [comment]
I still don't get what ESLint does which Standard can't do. However, if I have to choose I'll go with ESLint with the Standard rules
