### ISSUE TITLE
Check for Updates causes an error

### ISSUE THREAD

**Issue by antonyrod** [terkelg/ramme#55]
After starting the program JavaScript error occurs in duplicate.
The same error is reproduced and after selecting in the menu Help > Check for Updates.

http://i.imgur.com/kI0wsVx.png
http://i.imgur.com/ouVz8SY.png

```
        -

        Ramme 2.3.0 x64
        Electron 1.3.5
        win32 x64 10.0.10240
```

**Comment by terkelg** [comment]
Thanks for reporting! I plan to add auto-update, and this should fix issues like this
