### ISSUE TITLE
More streamlined purpose for back button

### ISSUE THREAD

**Issue by brandonmcconnell** [terkelg/ramme#64]
Could we make the back button work more similarly to how it does in Instagram. It's unique depending on what tab you're on. If I am on a user's page on the Explore tab and then switch the home feed tab, the back button should grey out. If I then click into a user's feed from the home tab, the back button should appear again, and when clicked, should take me 1 level up/back. In the Instagram app, the back button is not used to move through a history of actions but navigating back to the parent of the tab you're on. If I am on my home feed and switch back to the Explore tab where I had a user's profile up, the profile should still be up there in that tab (saves my place) and the back button will be opaque and enabled again. Currently, if I go to a user's profile in the Explore tab, the home tab lights up for some reason without me even switching tabs.

**Comment by terkelg** [comment]
The problem is that this is more of a web browser than a app, and therefore I only have the browser history to navigate.
