### ISSUE TITLE
No scrollbar in arch linux

### ISSUE THREAD

**Issue by Adrian-Benavente** [terkelg/ramme#69]
I can see no scrollbar in archlinux

**Comment by anatolinicolae** [comment]
Should you?
I know this is ok on macOS since you don't see any scrollbars if you're using Magic Mouse or Magic Trackpad, but if you connect a normal PC mouse the scrollbars magically appear.

**Comment by terkelg** [comment]
As @Adrian-Benavente said, there's actually no scrollbars 👍
