### ISSUE TITLE
Notifications and auto refresh

### ISSUE THREAD

**Issue by njuart** [terkelg/ramme#7]
Hi, nice stuff! I've been using lots of similar apps, but this one looks promising, clean and sophisticated. Any chance of getting notifications and auto refresh on mac or elsewhere? Thx, keep it in the same spirit.

**Comment by terkelg** [comment]
I'm looking for a solution to both refresh and notifications. Thanks for your suggestions!

**Comment by stephenkingsley** [comment]
the refresh I think it can not just `window.location.href`. I think it can use `iframe` to open a hidden new page, and then replace the show page. but this has a problem is that refresh speed is a little slower than web page.

**Comment by stephenkingsley** [comment]
Notification I think can use the same solution.

**Comment by terkelg** [comment]
Closing this for now
