### ISSUE TITLE
Linux: No tray icon, Program continues to run but has to be killed manually.

### ISSUE THREAD

**Issue by DroWnThePoor** [terkelg/ramme#71]
OS: Elementary OS Freya(0.3.-) which is Ubuntu 14.04.
I have no icon for Ramme in my tray, which uses Aptana, I'm sure this program is compatible with Aptana right? Any help appreicated.

**Comment by VoOoLoX** [comment]
https://github.com/electron/electron/pull/7319

This might help

**Comment by terkelg** [comment]
Thanks for helping put @VoOoLoX. I don't have any experience with this however - I plan to do a little rewrite, and support AppImage builds. This might fix it for future releases
