### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by emporeso2** [terkelg/ramme#72]
I launch the latest release Ramme-linux32-2.3.0 , i'am on ubuntu.

[https://framapic.org/ZGd0rQmFvIcb/fSaKdHWeGWc9.png](url)

[https://framapic.org/tyi0hEjkVaxE/nRH7xwvWL1e1.png](url)

**Comment by terkelg** [comment]
Hi @emporeso2  - Thank you so much for helping out and reporing this. I'm aware of the bug, and I plan to do a rewrite of Ramme soon. Duplicate of #70 #55
