### ISSUE TITLE
v3 branch

### ISSUE THREAD

**Issue by terkelg** [terkelg/ramme#76]
Hey folks.
I don't have time to finish Ramme v3 at the moment. If anybody want to help, you're more than welcome!

**Comment by anatolinicolae** [comment]
I've been busy as well lately but I'm getting back on it ASAP. Also, let us know if you want to contribute & we'll add you to the Slack channel.

**Comment by amadeu01** [comment]
Hi, I'd like to help. Do you have any directions of what I can help ?

**Comment by terkelg** [comment]
We could use a bit more clean up in the code base, structure and if you like you're more than welcome to look at photo upload 👍
