### ISSUE TITLE
[Opps, an error occured] in Linux 16.04

### ISSUE THREAD

**Issue by k13elle** [terkelg/ramme#8]
I just downloaded your project.
It gradually slow until it was not respond.
I closed and open it again.
It show like this.
![screenshot from 2016-08-25 09-19-17](https://cloud.githubusercontent.com/assets/9081217/17954417/1ea538de-6aa5-11e6-852b-e75614026a9b.png)

**Comment by ninjaprawn** [comment]
This is nothing to do with Ramme. It is a server side error.

**Comment by terkelg** [comment]
Yes, it's indeed a server side error from Instagram
