### ISSUE TITLE
Cannot see the Ramme window

### ISSUE THREAD

**Issue by jaywyeee** [terkelg/ramme#84]
Ramme isn't visible. I can see the preview but the window is invisible. This happened with v2.3.0 but I didn't really care as I didn't need to use Ramme. I downloaded v3.0.2 as I recently needed it again and the same thing happens.

![2017-01-22_18-56-11](https://cloud.githubusercontent.com/assets/19872495/22182299/9b1db76a-e0d4-11e6-9302-7d071a0945a9.png)

**Comment by seitbekir** [comment]
On my Ubuntu machine the promlem is like that. Ramme 3 not appear in top/right bar as it was with 2.3. So, If you close it, you have to kill process ans start again to see the window

**Comment by anatolinicolae** [comment]
I'm aware of this as I experienced it as well. Still couldn't figure out what was the problem since our code follows electron's guidelines... :unamused:

**Comment by RypeDub420** [comment]
On Windows, there is no icon for the Taskbar, but is a blank space.

Right clicking this brings up Show, GitHub, New Issue, Quit. All options function, and the process terminates when you choose quit.
