### ISSUE TITLE
Windows build only works on 64-Bit

### ISSUE THREAD

**Issue by Nenkai** [terkelg/ramme#85]
I'm using a 32-bit OS and had no issues before v3 came in. I cannot install Ramme as it says "64-bit Windows is required."

It works fine if i build it from source, though.

**Comment by anatolinicolae** [comment]
It looks like @terkelg added only 64 bit builds. We'll check it out and add a 32 bit release as well.

**Comment by anatolinicolae** [comment]
Can you check out the latest release @Nenkai?

**Comment by Nenkai** [comment]
@anatolinicolae Works flawlessly. Thanks for the quick fix

**Comment by anatolinicolae** [comment]
Yeah, known issues #82 and #84, looking forward to fix them in the next one :confounded:
