### ISSUE TITLE
32bit linux version

### ISSUE THREAD

**Issue by emporeso2** [terkelg/ramme#87]
Hi,

why there is no 32bit linux version ?

Thanks

**Comment by vsile** [comment]
+1

**Comment by MichaelTunnell** [comment]
> why there is no 32bit linux version ? 

Most distros are dropping support for 32-bit anyway so might not be worth the effort to maintain a package that can't be used on many distros.

64-bit has been around for over 13 years now . . . it's time to leave 32-bit behind.
