### ISSUE TITLE
Always shows "Open in app" button

### ISSUE THREAD

**Issue by erosenberg** [terkelg/ramme#88]
The "Open in app" button always shows and is kind of annoying. Sorry if this has been mentioned before!

**Comment by terkelg** [comment]
Thanks for reporting. Can you send me a screenshot?

**Comment by anatolinicolae** [comment]
No need, I'm aware of this and can fix it. Will do ASAP ;)

**Comment by erosenberg** [comment]
Ahh, thanks @anatolinicolae !!
And thanks @terkelg for the quick reply! Awesome app.

**Comment by anatolinicolae** [comment]
"Open in app" button removed together with the App Store button at the bottom. Available in the next release ;)
