### ISSUE TITLE
Remove the iOS app installation banner at login page

### ISSUE THREAD

**Issue by foreseaz** [terkelg/ramme#90]
Hi @terkelg , appreciate your great work of ramme.

Would you consider remove the Instagram iOS app banner at login page shown as following?

![image](https://cloud.githubusercontent.com/assets/5697641/22722119/d5babe7c-edef-11e6-8d64-0738cca38fe1.png)

It covered the DnD area, which is a little bit annoying = =, keep on the great work!

**Comment by anatolinicolae** [comment]
Added a new CSS rule which should keep working in the next Instagram versions as well.

**Comment by foreseaz** [comment]
@anatolinicolae so fast and great work!
