### ISSUE TITLE
Icon is not showing in Cinnamon desktop

### ISSUE THREAD

**Issue by IonutGherman** [terkelg/ramme#92]
![screenshot from 2017-02-11 21-14-59](https://cloud.githubusercontent.com/assets/16104032/22856706/c0e547bc-f09f-11e6-9459-3d0df193082e.png)

**Comment by anatolinicolae** [comment]
Known issue #84, give it a search.

**Comment by terkelg** [comment]
@anatolinicolae can you maybe have a look at the source code from v2, this is a new issue in v3 - It didn't happen before 👍

**Comment by anatolinicolae** [comment]
This icon bug appeared on Windows as well. Will definitely check v2 and copy whatever was there before hoping for a working fix.
