### ISSUE TITLE
Quiting the app doesn't shut it down

### ISSUE THREAD

**Issue by pi99y** [terkelg/ramme#93]
Hi,
I'm running Xubuntu 16.04 64bit and after I quit the app (click on the X icon) the window disappears but its process remains present. I noticed this since I cannot restart the app until I manually kill the "ramme" process.

Thanks for making the app btw! :)

**Comment by anatolinicolae** [comment]
This issue was discovered in issue #84. We'll fix it in the next release! ;)

**Comment by octacian** [comment]
Shouldn't this issue be considered a duplicate and further discussion merged with #84 (as mentioned originally)? The other issue had confirmations of the problem on Linux as well, so theoretically this one *is* a duplicate.

On sidenote, I think I might have a solution, but we'll see later.

**Comment by dimitrimarinho** [comment]
@anatolinicolae I want to collaborate with a project open source for improve my coding skills. Could I learn with this app ? I'm willing to help in this project in any area that I will not disturb.

**Comment by anatolinicolae** [comment]
@dimitrimarinho Feel free to create a branch of the master, start learning and maybe fixing issues. If you fix anything, just create a PR, we'll have a look at it and merge.
