### ISSUE TITLE
How to upgrade app? Or find which version is installed?

### ISSUE THREAD

**Issue by DroWnThePoor** [terkelg/ramme#94]
I installed this app some time ago on a variant of Ubuntu 14.04 64 bit , and I don't remember if I built it from a git-clone or installed it via deb. How can I find out which version I have installed? And also I 
see on the main page of this github that it has automatic updates, does that mean I do not need to install newer versions via deb?

**Comment by terkelg** [comment]
I'm actually nut sure if auto-update works on linux - let me look into that. Do you know that @anatolinicolae?

**Comment by anatolinicolae** [comment]
You should first remove old Ramme version with
`dpkg -r ramme`

Then you can get the latest AppImage and directly run, or get the latest deb and install with
`dpkg -i path/to/ramme.deb`

The AppImage should automatically update on new releases. Regarding the deb, you may see updates while running `apt update && apt list --upgradable`.

**Comment by DroWnThePoor** [comment]
@terkelg @anatolinicolae Thanks for taking the time to address my question, I feel like a lot of people who really need this app are Linux users in particular, just saying. Keep up the great work.
