### ISSUE TITLE
Closing "Instagram Find it Free in the App Store" message kills feed

### ISSUE THREAD

**Issue by kmslogic** [terkelg/ramme#95]
![image](https://cloud.githubusercontent.com/assets/1765725/23029406/a6662c9a-f427-11e6-8ac5-ae6ba5e69f28.png)

clicking the x to close this message causes the Instagram feed to disappear.  Only way to recover is to close ramme via the task manager in windows.

**Comment by terkelg** [comment]
Thanks for reporting the issue. We'll look into it.

**Comment by anatolinicolae** [comment]
I guess I missed that banner in the latest fix. Will dive into it again.
