### ISSUE TITLE
No Private / Direct Messages?

### ISSUE THREAD

**Issue by RypeDub420** [terkelg/ramme#98]
Why can every other feature be available unofficially, but not DM's / PM's?

**Comment by wa1id** [comment]
Wondering as well. The Official Windows App of Instagram has it. Too bad I can't find anything on Linux

**Comment by anatolinicolae** [comment]
@wa1id does it? Can you link me the Windows app?

**Comment by santimacia** [comment]
Is on the oficial marketplace
https://www.microsoft.com/en-us/store/p/instagram/9nblggh5l9xt

**Comment by MasterYushi** [comment]
I am looking for that too, can it be added?

**Comment by aranajhonny** [comment]
Just like this you need an api. Would be a good feature.

**Comment by terkelg** [comment]
Support for this will land when Instagram allow it in their web ui. I'm closing for now.

**Comment by fabiocaccamo** [comment]
I think that this issue should not be closed.

**Comment by bil-elmoussaoui** [comment]
@fabiocaccamo the Ramme application is a wrapper for the website with some + functionalities. As Instagram doesn't provide a way for accessing the DM messages we can't do anything about it. So this is issue was closed; once instagram implements that you will get it in time :+1:

**Comment by Fohlen** [comment]
There is one way or another. Have a look at https://github.com/ifedapoolarewaju/igdm which solved this issue nicely

**Comment by anatolinicolae** [comment]
@Fohlen they solved that using the Private API, but [we're working on that and have issues with the login as stated here](https://github.com/terkelg/ramme/commit/86d6becd6eed8f1cdccc95f12ffd212eeb63094b). Have you tried that app? Are you able to log in? Help us fix that in the Private API or contribute to the vuetify branch!

**Comment by Fohlen** [comment]
@anatolinicolae yes I'm running the current state-of-the-art git version and it works nicely. I will have a dig into the `vuetify` branch
